### ISSUE TITLE
ImportError: cannot import name 'strip_ansi'

### ISSUE THREAD

**Issue by cce-dsantos** [dbcli/mycli#1007]
Affected version: `mycli-1.24.1.dist-info`
Issued line content: `from cli_helpers.utils import strip_ansi`
Suggested fix: `import strip_ansi`
```
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 5, in <module>
    from mycli.main import cli
  File "/usr/local/lib/python3.6/site-packages/mycli/main.py", line 23, in <module>
    from cli_helpers.utils import strip_ansi
ImportError: cannot import name 'strip_ansi'
```

TLDR:
mycli is setting `cli_helper` to version 2.0.1 but `sqlparser` is rising the bar to 2.3.1, I suspect that this new `cli_helper` version has deprecated strip-ansi wrap, so to avoid this import error I referenced string-ansi lib straight way on main.py

does it help if I send out a PR?

**Comment by rolandwalker** [comment]
This seems to have been fixed.
