### ISSUE TITLE
libffi.so.7 removed from latest libffi packages

### ISSUE THREAD

**Issue by seagoj** [dbcli/mycli#1008]
Looks like libffi.so.7 has been removed in favor of libffi.so.8. Is it possible to migrate to libffi.so.8 or are there alternate installation instructions? I've downgraded for now, but getting back to current would be great!

Happy to help in any way I can.

**Comment by seagoj** [comment]
Hmm, maybe I'll have to dig into this further then, but it seems to be required on Arch linux. I'll add more detail when I'm back at my computer

**Comment by seagoj** [comment]
This is the error I receive without downgrading. Looks like it's required for terminaltables.

```
  Traceback (most recent call last):
    File "/home/seagoj/.local/bin/mycli", line 5, in <module>
    ¦ from mycli.main import cli
    File "/home/seagoj/.local/lib/python3.6/site-packages/mycli/main.py", line 19, in <module>
    ¦ from cli_helpers.tabular_output import TabularOutputFormatter
    File "/home/seagoj/.local/lib/python3.6/site-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    ¦ from .output_formatter import format_output, TabularOutputFormatter
    File "/home/seagoj/.local/lib/python3.6/site-packages/cli_helpers/tabular_output/output_formatter.py", line 10, in <module>
    ¦ from . import (delimited_output_adapter, vertical_table_adapter,
     File "/home/seagoj/.local/lib/python3.6/site-packages/cli_helpers/tabular_output/terminaltables_adapter.py", line 6, in <module>
    ¦ import terminaltables
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/__init__.py", line 9, in <module>
    ¦ from terminaltables.ascii_table import AsciiTable  # noqa
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/ascii_table.py", line 3, in <module>
    ¦ from terminaltables.base_table import BaseTable
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/base_table.py", line 3, in <module>
    ¦ from terminaltables.build import build_border, build_row, flatten
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/build.py", line 3, in <module>
    ¦ from terminaltables.width_and_alignment import visible_width
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/width_and_alignment.py", line 6, in <module>
    ¦ from terminaltables.terminal_io import terminal_size
    File "/home/seagoj/.local/lib/python3.6/site-packages/terminaltables/terminal_io.py", line 3, in <module>
    ¦ import ctypes
    File "/home/seagoj/.asdf/installs/python/3.6.2/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    ¦ from _ctypes import Union, Structure, Array
  ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by seagoj** [comment]
Actually, if I update terminaltables to latest I can get the error to go away, but it then fails on pyperclip. Maybe that's where this issue belongs?

**Comment by seagoj** [comment]
Nevermind. i think this was all due to an outdated python/pip. Nothing to see here...
