### ISSUE TITLE
'str' object has no attribute 'parent'

### ISSUE THREAD

**Issue by Atomnp** [dbcli/mycli#1027]
I installed `mycli` from AUR. when i try to use `show tables` it gives error as shown in title

```
sudo mycli -u root
Connecting to socket /var/run/mysqld/mysqld.sock, owned by user mysql
MariaDB 10.6.5
mycli 1.24.1
Home: http://mycli.net
Bug tracker: https://github.com/dbcli/mycli/issues
Thanks to the contributor - Zhidong
MariaDB root@(none):(none)> use practice;
You are now connected to database "practice" as user "root"
Time: 0.001s
MariaDB root@(none):practice> show tables;
'str' object has no attribute 'parent'
MariaDB root@(none):practice>
```

**Comment by Atomnp** [comment]
I also tried installing from `pip` but there is another issue using pip

```
sudo mycli -u root
Traceback (most recent call last):
  File "/home/atom/.local/bin//mycli", line 5, in <module>
    from mycli.main import cli
ModuleNotFoundError: No module named 'mycli
'```

**Comment by XuCcc** [comment]
same problem

**Comment by ifnk** [comment]
i have same problem

**Comment by amjith** [comment]
A new version was released today to fix the issue. Try upgrading with `pip install -U mycli`.

**Comment by Atomnp** [comment]
I tried the latest version, it does not seem to work.

**Comment by htto** [comment]
Same here, with cli_helpers 2.2.0 and mycli 1.24.2
```
2022-01-12 16:30:53,219 (271993/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded
    on, off = self.style_string[str(ttype)]
KeyError: \'Token.Output.TableSeparator\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mycli/main.py", line 711, in one_iteration
    formatted = self.format_output(
  File "/usr/lib/python3.10/site-packages/mycli/main.py", line 1029, in format_output
    formatted = self.formatter.format_output(
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output
    data, headers = f(data, headers, column_types=column_types, **fkwargs)
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output
    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>
    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt
    return tabulate.Line(
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>
    *(style_field(table_separator_token, val) for val in elt)
  File "/usr/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field
    formatter.format(((token, field),), s)
  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded
    ttype = ttype.parent
AttributeError: \'str\' object has no attribute \'parent\'
'
```

**Comment by amjith** [comment]
@htto is right. It is due to the latest version of pygments. I'm working on a more permanent solution, in the meantime if you can downgrade the pygments version using `pip install pygments==2.11.1` that should fix the issue for you. Sorry about the inconvenience.

**Comment by viswajitnayak** [comment]
> pip install -U mycli

working for me after upgrade.. thanks

**Comment by JSantangelo83** [comment]
Same problem here
```
mycli                         1.24.2
Pygments                  2.11.1
```
I tried upgrading mycli from pip, reinstalling from aur, but nothings seems to work, i keep getting 
```
MariaDB root@(none):testingdb> show tables
'str' object has no attribute 'parent'
```

**Comment by Alessandrostr95** [comment]
> A new version was released today to fix the issue. Try upgrading with `pip install -U mycli`.

It works for me, thanks!

**Comment by kumarvivek-dev** [comment]
for pgcli I was also getting the same error. After upgrading with "pip install -U pgcli" it worked for me. Thanks!
