### ISSUE TITLE
can't connect with empty password both for MySQL and TiDB

### ISSUE THREAD

**Issue by siddontang** [dbcli/mycli#1058]
Hi @amjith 

I tried to use mycli to connect TiDB with an empty password, but to my surprise, I typed Enter but nothing happened

```bash
mycli git:(main) ✗ mycli mysql://root@127.0.0.1:3306/test
Password:
Password:
Password:
Password:
```

The log here

```
2022-06-14 22:33:34,255 (95865/MainThread) mycli DEBUG - Initializing mycli logging.
2022-06-14 22:33:34,255 (95865/MainThread) mycli DEBUG - Log file '/Users/tangliu/.mycli.log'.
2022-06-14 22:33:34,255 (95865/MainThread) mycli.config DEBUG - Found login path file at '/Users/tangliu/.mylogin.cnf'
2022-06-14 22:33:34,257 (95865/MainThread) mycli.sqlexecute DEBUG - Connection DB Params:
	database: 'test'	user: 'root'	host: '127.0.0.1'	port: 4000	socket: None	charset: 'utf8'	local_infile: False	ssl: None	ssh_user: None	ssh_host: None	ssh_port: 22ssh_password: None	ssh_key_filename: None	init_command: None
2022-06-14 22:34:31,698 (95865/MainThread) mycli.main DEBUG - Database connection failed: Abort().
2022-06-14 22:34:31,704 (95865/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.9/site-packages/mycli/main.py", line 517, in connect\n    _connect()\n  File "/opt/homebrew/lib/python3.9/site-packages/mycli/main.py", line 468, in _connect\n    new_passwd = click.prompt(\'Password\', hide_input=True,\n  File "/opt/homebrew/lib/python3.9/site-packages/click/termui.py", line 166, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
```

https://user-images.githubusercontent.com/1080370/173748202-22da4d09-64ce-4829-a788-b1549bfbd6a7.mov

**Comment by laixintao** [comment]
Hi I have tried with the same connection args for both mysql server with password and without password, and can not reproduce.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/9675939/174095503-f2b6c73b-f53e-4b57-992e-e346318e1615.png">

Cloud you please:

1. try to upgrade to latest mycli (I tested under mycli 1.24.1)
2. then try to connect using `mycli mysql://root@127.0.0.1:3306 --login-path /dev/null`, because I saw `Found login path file at '/Users/tangliu/.mylogin.cnf'` from your logs.

thanks.

**Comment by amjith** [comment]
I suspect that the issue is from mylogin.cnf as well. 

I think mylogin.cnf has a password that mycli tries to use and when that doesn't work it shows the password prompt. But empty password is not handled by the prompt correctly and it gets into this weird state. 

I'd suggest trying the suggestion from @laixintao 

```
mycli mysql://root@127.0.0.1:3306/test --login-path /dev/null  
```

I'll look into why we can't accept empty string as an input for the password prompt.
