### ISSUE TITLE
sql statement contains "*" that has mysql spatial data format , i.e.  linestring,get below error.

### ISSUE THREAD

**Issue by hlee13** [dbcli/mycli#106]
2015-08-03 15:08:48,736 (9676/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py", line 357, in run_cli\n    for title, cur, headers, status in res:\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/sqlexecute.py", line 108, in run\n    yield self.execute_normal_sql(sql)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/sqlexecute.py", line 113, in execute_normal_sql\n    num_rows = cur.execute(split_sql)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/cursors.py", line 134, in execute\n    result = self._query(query)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/cursors.py", line 282, in _query\n    conn.query(q)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/connections.py", line 768, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/connections.py", line 929, in _read_query_result\n    result.read()\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/connections.py", line 1132, in read\n    self._read_result_packet(first_packet)\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/connections.py", line 1182, in _read_result_packet\n    self._get_descriptions()\n  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/pymysql/connections.py", line 1269, in _get_descriptions\n    assert eof_packet.is_eof_packet(), \'Protocol error, expecting EOF\'\nAssertionError: Protocol error, expecting EOF\n'

**Comment by amjith** [comment]
@hlee13 Can you paste the query here so I can try to reproduce this locally? 

It seems like the issue is coming from the MySQL adapter PyMySQL library. But if I have a reproducible case, I can at least file an issue with them to track it down. 

Thanks!

**Comment by hlee13** [comment]
SELECT * from table_xxx limit 1;

CREATE TABLE `table_xxx ` (
  `ID` bigint(20) NOT NULL,
  `geom` linestring NOT NULL,
  PRIMARY KEY (`ID`),
  SPATIAL KEY `geom` (`geom`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by amjith** [comment]
I just tried the commands you gave in my local instance of mycli and it works fine. 

<img width="941" alt="1__0_1_python2_7_-__mycli___users_amjith_newrelic_bam-react-test___tmux_" src="https://cloud.githubusercontent.com/assets/49260/9052820/0d0b9754-3a21-11e5-9908-8ebfe0f6e893.png">

If you're still seeing the error can you tell me what version of mysql you're using and what OS you're running?

**Comment by hlee13** [comment]
why limit 1 command, has no row. Maybe you have a empty table, so no error happened.

**Comment by hlee13** [comment]
mysql  Ver 14.14 Distrib 5.5.32
mycli Ver 1.2.0
Ubuntu Ver 12.04

**Comment by amjith** [comment]
I just noticed that my table was empty and the INSERT statement didn't quite work. 

So I inserted the data and tried again. I get the following error: 

```
'ascii' codec can't decode byte 0xf4 in position 22: ordinal not in range(128)
```

<img width="1153" alt="1__0_2_python2_7_-__mycli___users_amjith_newrelic_rpm_site_app_presenters___tmux_" src="https://cloud.githubusercontent.com/assets/49260/9053042/f4d4bd70-3a23-11e5-93ee-809c8c9950bd.png">

Is this what you're seeing as well?

**Comment by loslots** [comment]
I'm lost I don't understand this  at  all I just know my phone says it has numerous CSC codes applied

Sent from Yahoo Mail on Android

**Comment by hlee13** [comment]
yes, i also seen, I think major reason is mysql spatial data in table. In a word, it wonn't work.

**Comment by amjith** [comment]
I don't follow why you say that it won't work. 

I haven't tried to dig into it yet, but can you elaborate a little bit?

**Comment by danieljwest** [comment]
As far as I can tell that GeomFromText returns a byte array of some sort which is not meant to be rendered in the human readable world... which makes sense why the library would be having an issue. Modifying the pymysql connections.py to ignore the decode errors or to turn it into a hex string on an DecodeError exception produces semi readable content. Probably not the most elegant solution, but I'm not that familiar with pymysql. It would seem the mysql client renders this particular column as a string with the bad characters ignored and color codes stripped out. Pretty similar to how the python print function renders it. 

Did you open an issue with them?

**Comment by danieljwest** [comment]
Alternatively, we can swap to use_unicode=false in the pymysql connection and change format_output in main.py to do the decoding.

If you let me know what you think is best (Python isn't exactly my speciality) I can follow up with a ticket or put together a pull request for you.

**Comment by amjith** [comment]
@danieljwest I'd be interested to see how it works with use_unicode=false and doing the decoding ourselves. If it doesn't render in mysql's default client, I'm not really sure what we could be doing to make it better. 

I agree, even if we can't get it to render anything useful we should at least catch the error and gracefully degrade instead of throwing this obscure error message

**Comment by danieljwest** [comment]
Sounds good. I'll throw together a pull request in my spare time and see what I can come up with. Just tinkering I was able to get it past the error message and render on screen, but I need to explore what implications those changes would have.

I think converting a binary data type to hex will be a little cleaner than what the mysql client currently does. This way you'd theoretically be able to copy and paste it into an insert/update statement for a binary field.
