### ISSUE TITLE
An error occurred when the mycli command was executed

### ISSUE THREAD

**Issue by pptfz** [dbcli/mycli#1100]
install
```
pip3 install mycli
```

Operating system
```
$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

command
```
$ which mycli
/usr/local/bin/mycli
```

python version
```
$ python
python                    python2.7                 python3.6                 python3.6m                python3.6m-x86_64-config  
python2                   python3                   python3.6-config          python3.6m-config         python3-config            
```

Execution error
```
$ mycli --version
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 5, in <module>
    from mycli.main import cli
  File "/usr/local/lib/python3.6/site-packages/mycli/main.py", line 27, in <module>
    import sqlglot
  File "/usr/local/lib/python3.6/site-packages/sqlglot/__init__.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by amagnolo** [comment]
The same problem occurs in Rocky Linux release 8.7, after upgrading mycli to the current version.
A workaround is to revert to an older version:
`pip3 install mycli --upgrade mycli==1.25.0`

**Comment by pptfz** [comment]
> The same problem occurs in Rocky Linux release 8.7, after upgrading mycli to the current version. A workaround is to revert to an older version: `pip3 install mycli --upgrade mycli==1.25.0`

Thank you very much, I am the latest version installed by default and will not work properly in Centoss 7.9, Follow the method you provided to install version 1.25

**Comment by rolandwalker** [comment]
Hi!  The `mycli` code requires Python 3.7 or better.  How can we better document this?  Our CI is only running tests for 3.9+ since earlier versions of Python are EOL:

 * https://devguide.python.org/versions/

**Comment by rolandwalker** [comment]
Closing since only Python 3.10+ is supported now.
