### ISSUE TITLE
Database connection failed: error('unpack requires a buffer of 4 bytes').

### ISSUE THREAD

**Issue by bkysela** [dbcli/mycli#1146]
When connecting using `mycli` I see the following on the console.

```
$ mycli
Connecting to socket /var/run/mysqld/mysqlx.sock, owned by user mysql
unpack requires a buffer of 4 bytes
$ 
```

Running with DEBUG, this is in the log.

```
2024-01-17 12:16:16,402 (2797336/MainThread) mycli.sqlexecute DEBUG - Connection DB Params: 
        database: 'xxxxxxx'     user: 'xxxxxxxx'    host: xxxxx      port: xxxxx      socket: '/var/run/mysqld/mysqlx.sock'   charset: 'utf8' local_infile: False     ssl: None             ssh_user: None  ssh_host: None  ssh_port: 22    ssh_password: None      ssh_key_filename: None  init_command: None
2024-01-17 12:16:16,402 (2797336/MainThread) mycli.main DEBUG - Database connection failed: error('unpack requires a buffer of 4 bytes').
2024-01-17 12:16:16,402 (2797336/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/mycli/main.py", line 482, in connect\n    _connect()\n  File "/usr/lib/python3/dist-packages/mycli/main.py", line 456, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/usr/lib/python3/dist-packages/mycli/sqlexecute.py", line 119, in __init__\n    self.connect()\n  File "/usr/lib/python3/dist-packages/mycli/sqlexecute.py", line 177, in connect\n    conn = pymysql.connect(\n  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 632, in connect\n    self._get_server_information()\n  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1065, in _get_server_information\n    self.server_thread_id = struct.unpack("<I", data[i : i + 4])\nstruct.error: unpack requires a buffer of 4 bytes\n'
```

```
$ mycli --version
Version: 1.27.0
$ mysqld --version
/usr/sbin/mysqld  Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
```

The regular MySQL client connects without issue.

**Comment by dzdidi** [comment]
same problem on same OS verion

**Comment by asrul10** [comment]
Any update?
I had same issue with ubuntu 24.04, mysql 8.0.36, and mycli 1.27.0

**Comment by 8Everglow1** [comment]
same how to fix

**Comment by YoukeZhang** [comment]
You can try to add `-h127.0.0.1`, the same problem I had was fixed by adding this

**Comment by KamilMr** [comment]
> You can try to add `-h127.0.0.1`, the same problem I had was fixed by adding this

That line fixed the problem for me also. But I wonder why? Any hints to understand this?

**Comment by amjith** [comment]
This issue has been fixed in the latest version thanks to @lazmond3's persistent debugging. Try the latest version. Reopen the ticket if you're still having the problem.
