### ISSUE TITLE
mycli version is not up to date in Ubuntu and this causes a crash

### ISSUE THREAD

**Issue by vyshnav-vinod** [dbcli/mycli#1158]
While installing from `pip` , `mycli` works without any issues. But i tried to install using `apt` in my **Ubuntu 22.04** and it crashes with the below error.

```
MySQL 8.0.36
mycli 1.24.3
Home: http://mycli.net
Bug tracker: https://github.com/dbcli/mycli/issues
Thanks to the contributor - Karthikeyan Singaravelan
Traceback (most recent call last):
  File "/usr/bin/mycli", line 33, in <module>
    sys.exit(load_entry_point('mycli==1.24.3', 'console_scripts', 'mycli')())
  File "/home/vyshnav/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/vyshnav/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/vyshnav/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vyshnav/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mycli/main.py", line 1296, in cli
    mycli.run_cli()
  File "/usr/lib/python3/dist-packages/mycli/main.py", line 808, in run_cli
    reserve_space_for_menu=self.get_reserved_space(),
  File "/usr/lib/python3/dist-packages/mycli/main.py", line 1057, in get_reserved_space
    _, height = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'
```
Notice that the version of mycli in Ubuntu is `1.24.3` while the latest version available through `pip` is `1.27.2`. Is the packages for the distributions not being updated anymore?

**Comment by amjith** [comment]
We don't manage the debian packages. Our recommended way of installation is to use `pip` or `uv`. 

First install uv using https://docs.astral.sh/uv/getting-started/installation/

Then run `uv tool install mycli`. That should be enough to get the latest mycli. 

Feel free to reopen the issue if you're having trouble with the instructions.
