### ISSUE TITLE
feature request: support \G when multi_line is enabled

### ISSUE THREAD

**Issue by rvangsgaard** [dbcli/mycli#129]
When I have multi_line enabled is seems like \G is not recognised.

I use multi_line as it makes it difficult to make mistakes by accidentally hitting the Enter key - for example before adding the where clause to a delete :)

**Comment by amjith** [comment]
\G is recognized in the multi-line mode. But it has to be immediately followed by a semi-colon. 

For eg:

```
SELECT * 
FROM test_table
WHERE id > 10 \G;
```

But I think what you're requesting is to end the query with the \G and pressing enter will execute the query is that correct?

**Comment by amjith** [comment]
I've fixed this in master. Can you give it a try? You can install from master as follows:

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by rvangsgaard** [comment]
Why didn't I think of adding a semi-colon?!? Adding the semi-colon is all I need :) Thanks for showing me.

I get an error when installing from master:

```
/usr/bin/pip run on Wed Aug 12 21:02:40 2015
Downloading/unpacking https://github.com/dbcli/mycli/archive/master.zip
  Downloading from URL https://github.com/dbcli/mycli/archive/master.zip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 611, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
ZeroReturnError
```

**Comment by amjith** [comment]
That's a bit odd. I feel like it could be a transient error due to network connectivity. Can you try it again? 

If it still doesn't work you can try `easy_install https://github.com/dbcli/mycli/archive/master.zip`. 

Can you tell me how you had it installed originally? Was it done using brew?

**Comment by rvangsgaard** [comment]
I just got the exact same error. Then I tried again, and it worked - strange.

It works as expected now, I can use \G without semi-colon. Thank you.

Btw I am running Ubuntu Linux.
