### ISSUE TITLE
Mycli python error

### ISSUE THREAD

**Issue by liveNo** [dbcli/mycli#131]
When I use mycli, appeared error:

Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.3.0', 'console_scripts', 'mycli')()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 571, in cli
    mycli.run_cli()
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 282, in run_cli
    self.initialize_completions()
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 481, in initialize_completions
    return self.refresh_dynamic_completions()
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 490, in refresh_dynamic_completions
    completer.extend_database_names(sqlexecute.databases())
  File "/usr/lib/python2.6/site-packages/mycli/sqlexecute.py", line 157, in databases
    cur.execute(self.databases_query)
  File "/usr/lib/python2.6/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/usr/lib/python2.6/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 1132, in read
    self._read_result_packet(first_packet)
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 1182, in _read_result_packet
    self._get_descriptions()
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 1252, in _get_descriptions
    charset = charset_by_id(field.charsetnr)
  File "/usr/lib/python2.6/site-packages/pymysql/charset.py", line 34, in by_id
    return self._by_id[id]
KeyError: 0

What's wrong?

**Comment by amjith** [comment]
Sorry about the error. Can you tell me how you launched mycli and what command you ran to produce this error? 

It seems like mycli crashed at launch time. If that's true, can you send me the exact command you used to launch it? 

Can you also tell me if you installed it via `pip` or `debian` package?

**Comment by liveNo** [comment]
yeah, via pip installed package.

When I execute command mycli connected to the local database, it's OK. But When I connected the remote database, it will report the above error.

 I excute mysql connected remote database, it's normal.

**Comment by danieljwest** [comment]
The error implies an unexpected charset encoding came back and pymysql is having some trouble with it which would be pretty strange for a list of database names? 

Do you have any out of the ordinary database names? 
```sql
SHOW DATABASES
```

Also could you run the following on the problem mysql server? Perhaps the character sets are configured differently.
```sql
mysql -N -s -e "select id, character_set_name, collation_name, is_default from information_schema.collations order by id;"
```

**Comment by amjith** [comment]
Please reopen if you're still having issues.
