### ISSUE TITLE
Try to connect in a wrong host

### ISSUE THREAD

**Issue by robsonpeixoto** [dbcli/mycli#170]
I trying to connect on IP `192.168.99.100` but mycli try to connect in `192.168.99.1`

```bash
$ mycli -h '192.168.99.100' -uroot -proot -P3306
(1130, u"Host '192.168.99.1' is not allowed to connect to this MySQL server")
```

Log:
```
2015-10-15 11:11:31,261 (14101/MainThread) mycli DEBUG - Initializing mycli logging.
2015-10-15 11:11:31,262 (14101/MainThread) mycli DEBUG - Log file '~/.mycli.log'.
2015-10-15 11:11:31,262 (14101/MainThread) mycli.main ERROR - Error parsing u'/usr/local/etc/my.cnf'.
2015-10-15 11:11:31,262 (14101/MainThread) mycli.main ERROR - Recovering partially parsed config values.
2015-10-15 11:11:31,264 (14101/MainThread) mycli.main ERROR - Error parsing u'/usr/local/etc/my.cnf'.
2015-10-15 11:11:31,264 (14101/MainThread) mycli.main ERROR - Recovering partially parsed config values.
2015-10-15 11:11:31,264 (14101/MainThread) mycli.sqlexecute DEBUG - Connection DB Params:
	database: None	user: u'root'	host: u'192.168.99.100'	port: 3306	socket: u''
2015-10-15 11:11:31,271 (14101/MainThread) mycli.main DEBUG - Database connection failed: InternalError(1130, u"Host '192.168.99.1' is not allowed to connect to this MySQL server").
2015-10-15 11:11:31,272 (14101/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/lib/python2.7/site-packages/mycli/main.py", line 251, in connect\n    socket, charset)\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/lib/python2.7/site-packages/mycli/sqlexecute.py", line 38, in __init__\n    self.connect()\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/lib/python2.7/site-packages/mycli/sqlexecute.py", line 58, in connect\n    client_flag=pymysql.constants.CLIENT.INTERACTIVE)\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect\n    return Connection(*args, **kwargs)\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/connections.py", line 644, in __init__\n    self._connect()\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/connections.py", line 837, in _connect\n    self._get_server_information()\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/connections.py", line 1048, in _get_server_information\n    packet = self._read_packet()\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/connections.py", line 893, in _read_packet\n    packet.check_error()\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/connections.py", line 369, in check_error\n    err.raise_mysql_exception(self._data)\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception\n    _check_mysql_exception(errinfo)\n  File "/usr/local/Cellar/mycli/1.4.0/libexec/vendor/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception\n    raise InternalError(errno, errorvalue)\nInternalError: (1130, u"Host \'192.168.99.1\' is not allowed to connect to this MySQL server")\n'
```

**Comment by amjith** [comment]
That's a pretty serious bug. Since you closed it, does it mean you found a work around?

**Comment by robsonpeixoto** [comment]
Sorry. My bad.
