### ISSUE TITLE
Unable to pipe input

### ISSUE THREAD

**Issue by alasdairdc** [dbcli/mycli#179]
Not sure if this already fixed in master or not.  But using Debian Jessie and version 1.4.0 from the repo, attempting to pipe input into mycli 

```bash
$ zcat ~/create-test-db.sql.gz | mycli 
```

complains with: 

```bash
/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py:565: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('database', default='', nargs=1)
Version: 1.4.0
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Iryna Cherniavska
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.4.0', 'console_scripts', 'mycli')()
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py", line 590, in cli
    mycli.run_cli()
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py", line 347, in run_cli
    document = cli.run()
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 270, in run
    with self.input.raw_mode():
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/prompt_toolkit/input.py", line 65, in raw_mode
    return raw_mode(self.stdin.fileno())
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/prompt_toolkit/terminal/vt100_input.py", line 335, in __init__
    self.attrs_before = termios.tcgetattr(fileno)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by amjith** [comment]
This feature is not available yet. I've prioritized interactive commands first over the batch processing features like this.

**Comment by alasdairdc** [comment]
@amjith No problem I wasnt sure if it was a bug or just not implemented yet.

**Comment by amjith** [comment]
This is now available in the latest version. Forgot notify, sorry. 😞
