### ISSUE TITLE
check type of cli arguments before using them

### ISSUE THREAD

**Issue by Knorkebrot** [dbcli/mycli#190]
Something like a `Usage: ...` would be nice. At least don't crash :)

```
root@debian-wheezy:~# mycli --user foo -P bar baz
/usr/local/lib/python2.7/dist-packages/mycli/main.py:565: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('database', default='', nargs=1)
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.4.0', 'console_scripts', 'mycli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mycli/main.py", line 582, in cli
    mycli.connect(database, user, password, host, port, socket)
  File "/usr/local/lib/python2.7/dist-packages/mycli/main.py", line 242, in connect
    port = int(port or cnf['port'] or 3306)
ValueError: invalid literal for int() with base 10: 'bar'
```

**Comment by mdsrosa** [comment]
Nice catch, @Knorkebrot! That's really not cool. I'm looking into this right now and I'll make sure that this will be fixed before our next release. Thank you!

**Comment by mdsrosa** [comment]
This issue has been fixed. Thank you for reporting it, @Knorkebrot! :smile:

**Comment by Knorkebrot** [comment]
Great :+1:
