### ISSUE TITLE
mycli not loading on fresh OSX el Capitan install

### ISSUE THREAD

**Issue by dunolie** [dbcli/mycli#198]
[5079][2:34][me@comp] ~ ▶ brew update && brew install mycli
Already up-to-date.
==> Downloading https://homebrew.bintray.com/bottles/mycli-1.5.1.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mycli-1.5.1.el_capitan.bottle.tar.gz
==> Pouring mycli-1.5.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/mycli/1.5.1: 556 files, 6.1M
[5080][2:38][me@comp] ~ ▶ mycli
Traceback (most recent call last):
  File "/usr/local/Cellar/mycli/1.5.1/libexec/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.5.1', 'console_scripts', 'mycli')()
  File "/usr/local/Cellar/mycli/1.5.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/mycli/1.5.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/mycli/1.5.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/mycli/1.5.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/mycli/1.5.1/libexec/lib/python2.7/site-packages/mycli/main.py", line 639, in cli
    mycli.connect(database, user, password, host, port, socket)
  File "/usr/local/Cellar/mycli/1.5.1/libexec/lib/python2.7/site-packages/mycli/main.py", line 292, in connect
    port = int(port or cnf['port']) or 3306
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by amjith** [comment]
Yes. We released a buggy version. Sorry about that. I'm working to fix that soon. 

In the meantime you can still use mycli by providing a port number explicitly as follows: 

```
mycli -P 3306
```

**Comment by amjith** [comment]
This is now fixed in version 1.5.2. Please upgrade: 

```
brew update && brew upgrade mycli
```
