### ISSUE TITLE
error after install mycli using pip

### ISSUE THREAD

**Issue by asuna** [dbcli/mycli#211]
Hi,
I met error after install mycli, pls help me to solve this.
Thank you.

These are details:

````bash
root@misa:~/mycli# python -V && pip -V
Python 2.7.6
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

root@misa:~/mycli# mycli
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wcwidth' distribution was not found and is required by prompt-toolkit
````

**Comment by spacewander** [comment]
Try to Install `wcwidth`?
Run `pip install wcwidth` and see if the problem solved.

**Comment by amjith** [comment]
@asuna Try installing wcwidth as @spacewander had mentioned. You can also try reinstalling mycli.

```
pip uninstall mycli 

pip install -U mycli
```

That will uninstall the current copy of mycli and reinstall a new copy with it's dependencies.

**Comment by asuna** [comment]
@spacewander @amjith Works now. Thank you!
