### ISSUE TITLE
AWS EC2 Ubuntu

### ISSUE THREAD

**Issue by kklepper** [dbcli/mycli#249]
$ sudo apt-get install python-pip
    $ sudo apt-get install python-dev
    $ sudo pip install mycli
    $ mycli -uroot -p$MYSQL_ROOT_PASSWORD -h172.17.0.4 ci4
    Traceback (most recent call last):
      File "/usr/local/bin/mycli", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: wcwidth
    
What's wrong?

**Comment by tsroten** [comment]
Hello @kklepper! Thanks for using mycli. Can you try upgrading pip like this: `sudo pip install --upgrade pip`

Then, try `sudo pip uninstall mycli && sudo pip install mycli` to reinstall mycli.

If that doesn't work, can you post the output of `sudo pip list`

**Comment by kklepper** [comment]
Excellent! Thank you very much!

**Comment by kklepper** [comment]
Great to work with!
