### ISSUE TITLE
AttributeError: 'module' object has no attribute 'captureWarnings'

### ISSUE THREAD

**Issue by binarywang** [dbcli/mycli#256]
I have installed mycli on my CentOS 6.7, the python version is Python 2.6.6

but I got this error when trying to run mycli:

```
[root@localhost ~]# mycli
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.6.0', 'console_scripts', 'mycli')()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/usr/lib/python2.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 722, in cli
    auto_vertical_output=auto_vertical_output)
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 128, in __init__
    self.initialize_logging()
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 242, in initialize_logging
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'
```

**Comment by binarywang** [comment]
I tried to update python, but it didn't work.
I have commented the code in line 242 of /usr/lib/python2.6/site-packages/mycli/main.py, and it's ok now.

`  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 242, in initialize_logging
    logging.captureWarnings(True)`

**Comment by amjith** [comment]
Thanks for reporting it. This bug is now fixed in master.
