### ISSUE TITLE
There was a Exception when I pressed the space key after I typed 'show' command

### ISSUE THREAD

**Issue by smcdl** [dbcli/mycli#292]
percona eric@localhost:(none)> show Exception in thread Thread-5:
Traceback (most recent call last):           
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()                               
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python2.7/dist-packages/mycli/sqlcompleter.py", line 255, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/local/lib/python2.7/dist-packages/mycli/packages/completion_engine.py", line 85, in suggest_type
    full_text, identifier)                   
  File "/usr/local/lib/python2.7/dist-packages/mycli/packages/completion_engine.py", line 134, in suggest_based_on_last_token
    token_v = token.value.lower()            
AttributeError: 'tuple' object has no attribute 'value'

I don't get it what's wrong about it.Please tell me how to fix it, thank you.

**Comment by amjith** [comment]
This was because I didn't pin the dependency of sqlparse and the latest version has broken everything. 😭 

I'll try and fix that. In the meantime you can downgrade your sqlparse version and continue to use. Downgrading is done as follows: 

```
pip install sqlparse==0.1.19
```

Sorry about that.

**Comment by smcdl** [comment]
Thank you for you help. @
