### ISSUE TITLE
Exception  after input "show" and press tab or space

### ISSUE THREAD

**Issue by uuip** [dbcli/mycli#293]
mysql root@localhost:(none)> show Exception in thread Thread-5:
Traceback (most recent call last):         
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()                             
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python2.7/dist-packages/mycli/sqlcompleter.py", line 255, in get_completions           
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/local/lib/python2.7/dist-packages/mycli/packages/completion_engine.py", line 85, in suggest_type
    full_text, identifier)
  File "/usr/local/lib/python2.7/dist-packages/mycli/packages/completion_engine.py", line 134, in suggest_basn
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'

**Comment by amjith** [comment]
Duplicate #292

**Comment by uuip** [comment]
I have installed sqlparse,but this errow always that.
