### ISSUE TITLE
Using Spaces to the cause of the abnormal

### ISSUE THREAD

**Issue by lik0914** [dbcli/mycli#297]
Exception in thread Thread-6:
Traceback (most recent call last):     
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()                        
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python2.7/site-packages/mycli/sqlcompleter.py", line 255, in get_completions                              
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python2.7/site-packages/mycli/packages/completion_engine.py", line 85, in suggest_type
    full_text, identifier)
  File "/usr/lib/python2.7/site-packages/mycli/packages/completion_engine.py", line 134, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'

**Comment by amjith** [comment]
Duplicate #296. 

Fixed by #295
