### ISSUE TITLE
AutoCompletion Error = '(' Exception in thread Thread-51

### ISSUE THREAD

**Issue by pleycpl** [dbcli/mycli#369]
Hi,
After VARCHAR keyword, i am entering (
and then i am getting error like this
```sql
mariadb root@localhost:dbName> ALTER TABLE tableName ADD COLUMN newcolumn VARCHAR(Exception in thread Thread-51:
Traceback (most recent call last):                                                                  
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                             
    self.run()                                                                                      
  File "/usr/lib/python3.6/threading.py", line 864, in run                                          
    self._target(*self._args, **self._kwargs)                                                       
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run             
    completions = list(buffer.completer.get_completions(document, complete_event))                  
  File "/usr/lib/python3.6/site-packages/mycli/sqlcompleter.py", line 247, in get_completions                                                                                                                      
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 92, in suggest_type
    full_text, identifier)
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 197, in suggest_based_on_last_token
    return [{'type': 'column', 'tables': extract_tables(full_text)}]
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 154, in extract_tables
    return list(extract_table_identifiers(stream))
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 113, in extract_table_identifiers
    for item in token_stream:
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 79, in extract_from_part
    if is_subselect(item):
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 67, in is_subselect
    if not parsed.is_group():
TypeError: 'bool' object is not callable
=>>>>>> In here, program waiting, i am entering like this '255);', and then i press Enter. It shows below the line.
mariadb root@localhost:dbName> ALTER TABLE tableName ADD COLUMN newcolumn VARCHAR(255); -- again i press Enter.
Query OK, 0 rows affected
Time: 0.089s
mariadb root@localhost:dbName> \q

```

<p>and after that, coloration still work , but autocompletion doesn't work</p>

Thanks.

I am exiting mycli, then i am entry mycli. 
Same issue:
```
mariadb root@localhost:dbName> CREATE TABLE newTable (Exception in thread Thread-78:
Traceback (most recent call last):                                      
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner 
    self.run()                                                          
  File "/usr/lib/python3.6/threading.py", line 864, in run              
    self._target(*self._args, **self._kwargs)                           
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/mycli/sqlcompleter.py", line 247, in get_completions                                                                                                                      
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 92, in suggest_type
    full_text, identifier)
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 197, in suggest_based_on_last_token
    return [{'type': 'column', 'tables': extract_tables(full_text)}]
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 154, in extract_tables
    return list(extract_table_identifiers(stream))
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 113, in extract_table_identifiers
    for item in token_stream:
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 79, in extract_from_part
    if is_subselect(item):
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 67, in is_subselect
    if not parsed.is_group():
TypeError: 'bool' object is not callable

```

<p>I think issue parenthesis '(' </p>

**Comment by meeuw** [comment]
This seems to be related to the python-sqlparse library which is used by mycli, could you please tell us which version of mycli and python-sqlparse you're using?

**Comment by pleycpl** [comment]
```
$ pip freeze
...
sqlparse==0.2.3
...
```

**Comment by meeuw** [comment]
And which version of mycli? Could you please try the latest version of the master branch? (`pip install git+https://github.com/dbcli/mycli.git`)

**Comment by pleycpl** [comment]
```
$ mycli --version
Version: 1.8.1
$ sudo pip install git+https://github.com/dbcli/mycli.git
Collecting git+https://github.com/dbcli/mycli.git
  Cloning https://github.com/dbcli/mycli.git to /tmp/pip-3f8ruyjm-build
  Requirement already satisfied (use --upgrade to upgrade): mycli==1.8.1 from git+https://github.com/dbcli/mycli.git in /usr/lib/python3.6/site-packages
Requirement already satisfied: click>=4.1 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already satisfied: Pygments>=2.0 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already satisfied: prompt_toolkit<1.1.0,>=1.0.0 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already satisfied: PyMySQL>=0.6.2 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already satisfied: sqlparse<0.3.0,>=0.2.2 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Collecting pycryptodome (from mycli==1.8.1)
  Downloading pycryptodome-3.4.5.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 124kB/s 
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3.6/site-packages (from prompt_toolkit<1.1.0,>=1.0.0->mycli==1.8.1)
Requirement already satisfied: wcwidth in /usr/lib/python3.6/site-packages (from prompt_toolkit<1.1.0,>=1.0.0->mycli==1.8.1)
Installing collected packages: pycryptodome
  Running setup.py install for pycryptodome ... done
Successfully installed pycryptodome-3.4.5
$ mycli -u root
Password:
Version: 1.8.1
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Lincoln Loop
mariadb root@localhost:(none)> CREATE TABLE customers (Exception in thread Thread-20:
Traceback (most recent call last):                                     
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()                                                         
  File "/usr/lib/python3.6/threading.py", line 864, in run             
    self._target(*self._args, **self._kwargs)                          
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/mycli/sqlcompleter.py", line 247, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 92, in suggest_type
    full_text, identifier)                                             
  File "/usr/lib/python3.6/site-packages/mycli/packages/completion_engine.py", line 197, in suggest_based_on_last_token
    return [{'type': 'column', 'tables': extract_tables(full_text)}]   
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 154, in extract_tables
    return list(extract_table_identifiers(stream))                     
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 113, in extract_table_identifiers
    for item in token_stream:
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 79, in extract_from_part
    if is_subselect(item):
  File "/usr/lib/python3.6/site-packages/mycli/packages/parseutils.py", line 67, in is_subselect
    if not parsed.is_group():
TypeError: 'bool' object is not callable

```

**Comment by meeuw** [comment]
I think this is related to 71f503afb699b2a8365f9e8fddcdddb1960a1e79 and this is in master so I'm not sure why this isn't fixed for you. Maybe you should add add --upgrade to pip install...

**Comment by tsroten** [comment]
@pleycpl I replicated your error (with installing from GitHub). Like @meeuw said, using `pip install --upgrade git+https://github.com/dbcli/mycli.git` worked for me.

I'm sorry this is still an issue. I'll have a new release of mycli out shortly.

**Comment by pleycpl** [comment]
Yeahh, it is working. Thanks a lot. 
```
$ sudo pip install --upgrade git+https://github.com/dbcli/mycli.git
[sudo] password for <Username>: 
Collecting git+https://github.com/dbcli/mycli.git
  Cloning https://github.com/dbcli/mycli.git to /tmp/pip-e0h4fpsb-build
Requirement already up-to-date: click>=4.1 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: Pygments>=2.0 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: prompt_toolkit<1.1.0,>=1.0.0 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: PyMySQL>=0.6.2 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: sqlparse<0.3.0,>=0.2.2 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: configobj>=5.0.6 in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: pycryptodome in /usr/lib/python3.6/site-packages (from mycli==1.8.1)
Requirement already up-to-date: six>=1.9.0 in /usr/lib/python3.6/site-packages (from prompt_toolkit<1.1.0,>=1.0.0->mycli==1.8.1)
Requirement already up-to-date: wcwidth in /usr/lib/python3.6/site-packages (from prompt_toolkit<1.1.0,>=1.0.0->mycli==1.8.1)
Installing collected packages: mycli
  Found existing installation: mycli 1.8.1
    Uninstalling mycli-1.8.1:
      Successfully uninstalled mycli-1.8.1
  Running setup.py install for mycli ... done
Successfully installed mycli-1.8.1
$ mycli --help
...
 --csv                         Display batch output in CSV format.
...
$ mycli -u root
Password: 
Version: 1.8.1
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - jweiland.net
mariadb root@localhost:(none)> show DATABASES;
Time: 0.003s
mariadb root@localhost:(none)> use dbName;
Time: 0.002s
mariadb root@localhost:dbName> show tables;
Time: 0.002s
mariadb root@localhost:dbName> CREATE TABLE github (name VARCHAR(15) );
Time: 0.043s
mariadb root@localhost:dbName> show tables;
```
