### ISSUE TITLE
Trouble with mycli installation 

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#385]
I have a VM setup (using Vagrant with Virtual Box) and running into errors.  I have tried the following (see below).  I have used mycli with other VM instances (using same stack) and all has worked fine?

```
$ pip install mycli
```

This runs fine but when executing `mycli` it cant be found (and I cant seem to find it manually either (where does it store the files)

```
$ brew install mycli
```

This has a bigger issue (see log below).

```
Error: uninitialized constant Language::Python::Virtualenv
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/vagrant/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/mycli.rb:2:in `<class:Mycli>'
/home/vagrant/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/mycli.rb:1:in `load_formula'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/vagrant/.linuxbrew/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/home/vagrant/.linuxbrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/home/vagrant/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/home/vagrant/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/home/vagrant/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
/home/vagrant/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by mikeerickson** [comment]
Issued cleared...

- removed all remnants manually
- rebooted VM
- $ sudo pip install mycli
- all working now
