### ISSUE TITLE
error on RHEL6.2 with python 2.6

### ISSUE THREAD

**Issue by romber2001** [dbcli/mycli#397]
i got error on RHEL6.2 with python 2.6, i tried both using pip and easy_install, the issue does not disappeared,waiting for your help,thanks in advance.
#102 

```
[root@hc09 yum.repos.d]# mycli --help
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.9.0', 'console_scripts', 'mycli')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 304
    return {x: get(x) for x in keys}
                        ^
SyntaxError: invalid syntax
```

**Comment by meeuw** [comment]
Hi @romber2001 as far as I know we don't support Python 2.6. I really recommend using Python from https://ius.io or https://fedoraproject.org/wiki/EPEL when using mycli on RHEL6.

As a side note, I'm working on getting mycli + dependencies on https://copr.fedorainfracloud.org/

**Comment by tsroten** [comment]
@romber2001 Also, see #414 if you want to install mycli with Python 2.6.

**Comment by tsroten** [comment]
I hope you were able to get this installed. I'm going to close this for now, feel free to open it back up if you'd like 😄
