### ISSUE TITLE
AttributeError: 'Application' object has no attribute 'pre_run_callables'

### ISSUE THREAD

**Issue by ChillarAnand** [dbcli/mycli#468]
mycli crashes for any command with this error

```
mycli -u root   
Password: 
Version: 1.10.0
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Prathap Ramamurthy
mysql root@localhost:(none)> use foo;
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/py35/bin/mycli", line 11, in <module>
    sys.exit(cli())
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/mycli/main.py", line 840, in cli
    mycli.run_cli()
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/mycli/main.py", line 645, in run_cli
    one_iteration()
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/mycli/main.py", line 485, in one_iteration
    document = self.handle_editor_command(self.cli, document)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/mycli/main.py", line 425, in handle_editor_command
    saved_callables = cli.application.pre_run_callables
AttributeError: 'Application' object has no attribute 'pre_run_callables'
```

**Comment by tsroten** [comment]
@ChillarAnand Hello! I'm sorry this is happening. Can you please let us know what version of prompt toolkit you're running:
```bash
$ pip show prompt-toolkit
```

**Comment by ChillarAnand** [comment]
@tsroten Thanks for quick reply.

```
Name: prompt-toolkit
Version: 1.0.14
Summary: Library for building powerful interactive command lines in Python
Home-page: https://github.com/jonathanslenders/python-prompt-toolkit
Author: Jonathan Slenders
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages
Requires: wcwidth, six
```

**Comment by tsroten** [comment]
@ChillarAnand Hmm, that's definitely odd. I'm having trouble reproducing this. Can you provide some more information?

1. How did you install mycli?
2. What's the output of `pip freeze`?

Thanks!!

**Comment by ChillarAnand** [comment]
I used pip to install it in a venv.

```
ak-androguard==3.2.8
ak-construct==2.5.2
ak-gchartwrapper==0.9.1
ak-isign==0.9.3
ak-postmonkey==1.0b1
ak-syntribos==0.3.1.dev91
ak-vendor==0.9.26
ak-vendoroo==1.9.7
alabaster==0.7.9
altgraph==0.13
alyn==0.1.1
amqp==1.4.9
androguard==3.0
ansible==2.3.1.0
anyjson==0.3.3
appdirs==1.4.3
appknox==1.2.2
appnope==0.1.0
argh==0.26.2
argon2-cffi==16.3.0
args==0.1.0
arrow==0.10.0
astroid==1.4.9
attrs==16.3.0
Automat==0.5.0
autopep8==1.3.1
awesome-slugify==1.6.5
awscli==1.11.28
Babel==2.3.4
babelfish==0.5.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
billiard==3.3.0.23
binaryornot==0.4.0
biplist==0.9
bleach==1.5.0
blinker==1.4
boto==2.46.1
boto3==1.4.4
botocore==1.4.85
brotlipy==0.6.0
bumpversion==0.5.3
cairocffi==0.7.2
CairoSVG==2.0.0
celery==3.1.25
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.4
click==6.7
cliff==2.7.0
clint==0.5.1
cloudpickle==0.2.2
cmd2==0.7.2
colorama==0.3.7
colosseum==0.1.6
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
construct==2.8.11
contextlib2==0.5.4
cookiecutter==1.5.1
coreapi==2.1.1
coverage==4.4.1
cowpy==1.0.1
cryptography==1.7.2
cssselect==1.0.0
cssutils==1.0.2
cycler==0.10.0
debtcollector==1.15.0
decorator==4.0.11
defusedxml==0.5.0
dicttoxml==1.7.4
diff-match-patch==20121119
Django==1.10.7
django-activity-stream==0.6.3
django-allauth==0.32.0
django-appconf==1.0.2
django-autotranslate==1.0.0
django-bootstrap3==7.1.0
django-braces==1.11.0
django-configurations==2.0
django-cors-headers==1.3.1
django-coverage-plugin==1.5.0
django-crispy-forms==1.6.1
django-debug-toolbar==1.8
django-environ==0.4.3
django-extensions==1.7.9
django-filter==1.0.4
django-formtools==1.0
django-grappelli==2.9.1
django-import-export==0.5.1
django-modeltranslation==0.12
django-model-utils==3.0.0
django-nose==1.4.4
django-redis==4.8.0
django-redis-cache==1.7.1
djangorestframework==3.6.3
djangorestframework-camel-case==0.2.0
djangorestframework-jwt==1.9.0
django-rest-multiple-models==1.8.1
django-rest-swagger==2.1.0
django-rq==0.9.5
django-silk==1.0.0
django-storages-redux==1.3.2
django-test-plus==1.0.17
django-tokenapi==0.2.5
django-unique-upload==0.2.1
django-versatileimagefield==1.7.0
dj-database-url==0.4.2
docopt==0.6.2
docutils==0.13.1
dogpile.cache==0.6.2
doit==0.30.3
EasyProcess==0.2.3
editdistance==0.3.1
EditorConfig==0.12.1
-e git+git@github.com:appknox/attackapi.git@a34be47ec6cbe5787256b5dbda145f0dcae38365#egg=attackapi
-e git+git@github.com:appknox/isign.git@875f3d1e4f179283c7a2b702ac90899e67411373#egg=isign
-e git+git@github.com:ChillarAnand/chamanti_ocr.git@52a19dc050aee8ea981ecf697450f6e2ad267b77#egg=chamanti_ocr
-e git+git@github.com:ChillarAnand/httpie-token-auth.git@d4720e4c5b8f4e143ffc797d1829cf937fba1c49#egg=httpie_token_auth
-e git+git@github.com:ChillarAnand/importmagic.git@45b0bddd5a973862a8661c89b624973e8d24123f#egg=importmagic
-e git+git@github.com:ChillarAnand/netra.git@763315cc9a8276f8c609f7e1d0463e47cbf8f13e#egg=netra
entrypoints==0.2.2
enzyme==0.4.1
factory-boy==2.8.1
Faker==0.7.17
falcon==1.0.0
feedparser==5.2.1
flake8==3.3.0
Flask==0.12
flower==0.9.1
frida==9.1.17
future==0.16.0
futures==3.0.5
gevent==1.2.1
ghp-import2==1.0.1
github3.py==0.9.6
gmvault==1.9.1
google-api-python-client==1.6.2
goslate==1.5.1
greenlet==0.4.12
grip==4.3.2
guessit==2.1.1
gunicorn==19.7.1
h2==2.6.0
HamlPy3==0.84.0
hiredis==0.2.0
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
httpie==0.9.9
httplib2==0.10.3
hug==2.2.0
humanize==0.5.1
hyperframe==4.0.2
idna==2.5
imagesize==0.7.1
IMAPClient==0.13
incremental==16.10.1
inflection==0.3.1
ipdb==0.10.3
ipykernel==4.5.2
ipython==6.0.0.dev0
ipython-genutils==0.1.0
ipywidgets==5.2.2
iso8601==0.1.11
isort==4.2.5
itsdangerous==0.24
itypes==1.1.0
jedi==0.10.0
Jinja2==2.8
jinja2-time==0.2.0
jira==1.0.10
jmespath==0.9.0
jsbeautifier==1.6.11
jsonpatch==1.15
jsonpointer==1.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.0
jupyter-console==5.1.0
jupyter-core==4.3.0
kaitaistruct==0.6
keystoneauth1==2.21.0
kombu==3.0.37
lazy-object-proxy==1.2.2
learnpypackaging==3.0.1
livestreamer==1.12.2
Logbook==0.10.1
lxml==3.7.3
macholib==1.8
Mako==1.0.6
Markdown==2.6.8
MarkupSafe==0.23
matplotlib==2.0.0
mccabe==0.6.1
memoizer==0.0.1
minio==2.0.5
mistune==0.7.3
mitmproxy==2.0.1
model-mommy==1.3.1
monotonic==1.3
msgpack-python==0.4.8
mycli==1.10.0
natsort==5.0.2
nbconvert==4.3.0
nbformat==4.2.0
ndg-httpsclient==0.4.2
netaddr==0.7.19
netifaces==0.10.6
networkx==1.11
newrelic==2.86.1.66
Nikola==7.8.3
nose==1.3.7
notebook==4.3.0
numpy==1.12.1
oauth2client==4.0.0
oauthlib==2.0.1
olefile==0.44
opbeat==3.5.2
openapi-codec==1.2.1
orm-choices==0.2.0
osc-lib==1.6.0
os-client-config==1.27.0
oslo.config==4.5.0
oslo.i18n==3.15.3
oslo.serialization==2.18.0
oslo.utils==3.26.0
packaging==16.8
pandas==0.19.2
pandocfilters==1.4.1
paramiko==2.1.2
parsel==1.1.0
passlib==1.7.1
path-and-address==2.0.1
pathtools==0.1.2
pbr==3.0.1
pdfkit==0.6.1
pexpect==4.2.1
pgcli==1.6.0
pgspecial==1.8.0
pickleshare==0.7.4
piexif==1.0.12
pika==0.10.0
Pillow==4.1.1
pirate-get==0.2.10
pkg-resources==0.0.0
pluggy==0.4.0
plumbum==1.6.3
polib==1.0.8
positional==1.1.1
poyo==0.4.0
prettytable==0.7.2
prompt-toolkit==1.0.14
protobuf==3.3.0
psycopg2==2.7.1
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.2.3
pyasn1-modules==0.0.8
PyAutoGUI==0.9.36
pyaxmlparser==0.1.4
pycodestyle==2.3.1
pycparser==2.17
pycrypto==2.6.1
pycryptodome==3.4.6
pycurl==7.43.0
PyDispatcher==2.0.5
pyflakes==1.5.0
pyflash==0.2.2
pygame==1.9.3
Pygments==2.2.0
pyinotify==0.9.6
PyJWT==1.4.2
pylint==1.6.5
PyMsgBox==1.0.6
PyMySQL==0.7.11
pyOpenSSL==0.15.1
pypandoc==1.3.3
pyparsing==2.2.0
PyPDF2==1.26.0
pyperclip==1.5.27
Pyphen==0.9.4
pyresttest==1.7.1
Pyro4==4.55
PyRSS2Gen==1.1
pyscreenshot==0.4.2
PyScreeze==0.1.11
pyserial==3.3
pysrt==1.1.1
pytesseract==0.1.7
pytest==3.0.6
pytest-cov==2.4.0
pytest-django==3.1.2
pytest-ipdb==0.1.dev2
pytest-sugar==0.8.0
python3-openid==3.1.0
python3-protobuf==2.5.0
python-cinderclient==2.2.0
python-dateutil==2.6.0
python-glanceclient==2.7.0
python-http-client==1.2.3
python-keystoneclient==3.11.0
python-logstash==0.4.6
python-mimeparse==1.6.0
python-neutronclient==6.3.0
python-novaclient==9.0.0
python-xlib==0.19
PyTweening==1.0.3
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.2.1
queuelib==1.4.2
rarfile==3.0
raven==6.0.0
rcssmin==1.0.6
rebulk==0.8.2
redis==2.10.5
redispy==3.0.0
regex==2017.6.23
reportlab==3.3.0
requests==2.17.3
requests-cache==0.4.13
requestsexceptions==1.2.0
requests-oauthlib==0.7.0
requests-toolbelt==0.7.0
rfc3986==1.0.0
rjsmin==1.0.12
rope==0.10.5
rpyc==3.3.0
rq==0.8.0
rsa==3.4.2
ruamel.yaml==0.13.14
s3transfer==0.1.10
saws==0.4.1
schedule==0.4.3
scipy==0.18.1
Scrapy==1.3.3
sendgrid==2.2.1
sendgrid-django==4.0.4
serpent==1.19
service-identity==16.0.0
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.10.0
six==1.10.0
slacker==0.9.30
slacker-log-handler==1.3.0
smtpapi==0.3.1
snowballstemmer==1.2.1
sortedcontainers==1.5.7
Sphinx==1.6.2
sphinxcontrib-websupport==1.0.1
sphinx-rtd-theme==0.1.9
sqlparse==0.2.3
stdlib-list==0.4.0
stevedore==1.23.0
stripe==1.43.0
subliminal==2.0.5
syntribos==0.3.1.dev89
tablib==0.11.4
tensorflow==1.1.0
termcolor==1.1.0
terminado==0.6
testpath==0.3
Theano==0.9.0
tinycss==0.4
tlslite==0.4.9
toga==0.2.8
toga-core==0.2.8
toga-demo==0.2.5
toga-gtk==0.2.8
tornado==4.2
tox==2.5.0
traitlets==4.3.1
translation==1.0.5
tvdb-api==1.10
tvoverlord==1.4.10
Twisted==17.1.0
Unidecode==0.4.20
uritemplate==3.0.0
uritemplate.py==3.0.2
urllib3==1.21.1
urwid==1.3.1
validate-email==1.3
veryprettytable==0.8.1
vine==1.1.3
virtualenv==15.1.0
vulture==0.13
w3lib==1.17.0
warlock==1.2.0
watchdog==0.8.3
wcwidth==0.1.7
WeasyPrint==0.33
webassets==0.12.1
webencodings==0.5
Werkzeug==0.12.2
whichcraft==0.4.0
whitenoise==3.3.0
widgetsnbextension==1.2.6
wrapt==1.10.10
ws4py==0.3.5
yapf==0.16.0
Yapsy==1.11.223
youtube-dl==2017.5.14
zope.interface==4.3.3
```

**Comment by tsroten** [comment]
@ChillarAnand So, I replicated your virtual environment, but can't reproduce this problem. Let's try removing and reinstalling (not from cache) mycli and prompt-toolkit:
```bash
pip uninstall -y prompt-toolkit mycli && pip install --no-cache-dir mycli
```

@j-bennet This might be up your alley. Any ideas?

**Comment by ChillarAnand** [comment]
Thanks for the help @tsroten. That fixed the issue. 

Any reason to enable pager by default?

**Comment by tsroten** [comment]
Great! I'm glad it's working.

Mycli's next release will, by default, only use the pager if the output doesn't fit on the screen. Hopefully that's more intuitive :)

**Comment by ChillarAnand** [comment]
Excellent design decision. Thanks to all contributors for building such an awesome tool!

**Comment by louisguitton** [comment]
Wow, I had the same issue with pgcli. And your solution @tsroten worked for me
