### ISSUE TITLE
Running a commented command beginning with "--" or "# " crashes mycli

### ISSUE THREAD

**Issue by richrd** [dbcli/mycli#497]
How to reproduce:
- Run any input beginning with `--` (even just inputting two dashes causes a crash)
- Run any input beginning with `# ` (must have a space and at least a single character after it)

Error message:
```
mariadb root@localhost:(none)> --asd
Traceback (most recent call last):
  File "/usr/bin/mycli", line 11, in <module>
    load_entry_point('mycli==1.8.1', 'console_scripts', 'console')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/mycli/mycli/main.py", line 807, in cli
    mycli.run_cli()
  File "/usr/share/mycli/mycli/main.py", line 511, in run_cli
    destroy = confirm_destructive_query(document.text)
  File "/usr/share/mycli/mycli/main.py", line 927, in confirm_destructive_query
    if is_destructive(queries) and sys.stdin.isatty():
  File "/usr/share/mycli/mycli/main.py", line 916, in is_destructive
    return queries_start_with(queries, keywords)
  File "/usr/share/mycli/mycli/main.py", line 910, in queries_start_with
    if query and query_starts_with(query, prefixes) is True:
  File "/usr/share/mycli/mycli/main.py", line 905, in query_starts_with
    return formatted_sql.split()[0] in prefixes
IndexError: list index out of range
```

**Comment by j-bennet** [comment]
@richrd Thanks for the report! We'll look into it.

**Comment by j-bennet** [comment]
@richrd Actually mycli does not display this behavior in the latest version.

The latest mycli behavior is:

* ignoring all the correctly formatted comments (there should be a space after a comment):

```
mysql root@localhost:(none)> -- select 1
Query OK, 0 rows affected
Time: 0.000s
mysql root@localhost:(none)> # select 1
Query OK, 0 rows affected
Time: 0.000s
mysql root@localhost:(none)> /* foo select 1 */
Query OK, 0 rows affected
Time: 0.000s
```

* displaying a SQL syntax error if the comments were not correctly formatted (no space after a comment):

```
mysql root@localhost:(none)> --select 1
(1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--select 1' at line 1")
```

What version are you on @richrd , and is it possible for you to update (`pip install -U mycli`)?

**Comment by j-bennet** [comment]
Didn't notice this at first - looks like you're using 1.8.1, mine is 1.12.1.

I suggest upgrading mycli if possible.

**Comment by tsroten** [comment]
I think mycli >= 1.9 has the fix for this.

**Comment by richrd** [comment]
Oops, really sorry to report something that's already fixed. My bad. Yes I'm on 1.8.1 but installed it from debian/ubuntu repos so I thought it was the latest version. I'll update right away!

**Comment by tsroten** [comment]
@richrd No problem at all! If you come across anything else, let us know 😄 !
