### ISSUE TITLE
Wrong Start Info Like Traceback (most recent call last)

### ISSUE THREAD

**Issue by houyaerda** [dbcli/mycli#514]
This fault is first after I insert lots of sql from a file of sql.
Then I restart mycli report wrong info like below:

`Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 11, in <module>
    load_entry_point('mycli==1.12.0', 'console_scripts', 'mycli')()
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/mycli/main.py", line 959, in cli
    mycli.run_cli()
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/mycli/main.py", line 654, in run_cli
    one_iteration()
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/mycli/main.py", line 475, in one_iteration
    document = self.cli.run()
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 413, in run
    self._redraw()
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/renderer.py", line 436, in render
    extended_height=size.rows,
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 157, in write_to_screen
    c.write_to_screen(cli, screen, mouse_handlers, WritePosition(xpos, ypos, width, s))
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 398, in write_to_screen
    self.content.write_to_screen(cli, screen, mouse_handlers, write_position)
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 157, in write_to_screen
    c.write_to_screen(cli, screen, mouse_handlers, WritePosition(xpos, ypos, width, s))
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 1087, in write_to_screen
    always_hide_cursor=self.always_hide_cursor(cli))
  File "/usr/local/Cellar/mycli/1.12.0/libexec/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 1209, in _copy_body
    for y in range(ypos, ypos + write_position.height):
TypeError: integer argument expected, got float`

ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

mycli --version
Version: 1.12.0

Thank you first.

**Comment by houyaerda** [comment]
.myclirc
`# vi: ft=dosini
[main]

# Enables context sensitive auto-completion. If this is disabled the all
# possible completions will be listed.
smart_completion = True

# Multi-line mode allows breaking up the sql statements into multiple lines. If
# this is set to True, then the end of the statements must have a semi-colon.
# If this is set to False then sql statements can't be split into multiple
# lines. End of line (return) is considered as the end of the statement.
multi_line = False

# Destructive warning mode will alert you before executing a sql statement
# that may cause harm to the database such as "drop table", "drop database"
# or "shutdown".
destructive_warning = True

# log_file location.
log_file = ~/.mycli.log

# Default log level. Possible values: "CRITICAL", "ERROR", "WARNING", "INFO"
# and "DEBUG". "NONE" disables logging.
log_level = INFO

# Log every query and its results to a file. Enable this by uncommenting the
# line below.
# audit_log = ~/.mycli-audit.log

# Timing of sql statments and table rendering.
timing = True

# Table format. Possible values: ascii, double, github,
# psql, plain, simple, grid, fancy_grid, pipe, orgtbl, rst, mediawiki, html,
# latex, latex_booktabs, textile, moinmoin, jira, vertical, tsv, csv.
# Recommended: ascii
table_format = ascii

# Syntax coloring style. Possible values (many support the "-dark" suffix):
# manni, igor, xcode, vim, autumn, vs, rrt, native, perldoc, borland, tango, emacs,
# friendly, monokai, paraiso, colorful, murphy, bw, pastie, paraiso, trac, default,
# fruity.
# Screenshots at http://mycli.net/syntax
syntax_style = default

# Keybindings: Possible values: emacs, vi.
# Emacs mode: Ctrl-A is home, Ctrl-E is end. All emacs keybindings are available in the REPL.
# When Vi mode is enabled you can use modal editing features offered by Vi in the REPL.
key_bindings = emacs

# Enabling this option will show the suggestions in a wider menu. Thus more items are suggested.
wider_completion_menu = False

# MySQL prompt
# \D - The full current date
# \d - Database name
# \h - Hostname of the server
# \m - Minutes of the current time
# \n - Newline
# \P - AM/PM
# \p - Port
# \R - The current time, in 24-hour military time (0–23)
# \r - The current time, standard 12-hour time (1–12)
# \s - Seconds of the current time
# \t - Product type (Percona, MySQL, Mariadb)
# \u - Username
prompt = '\t \u@\h:\d> '
prompt_continuation = '-> '

# Skip intro info on startup and outro info on exit
less_chatty = True

# Use alias from --login-path instead of host name in prompt
login_path_as_host = False

# Cause result sets to be displayed vertically if they are too wide for the current window,
# and using normal tabular format otherwise. (This applies to statements terminated by ; or \G.)
auto_vertical_output = False

# keyword casing preference. Possible values "lower", "upper", "auto"
keyword_casing = auto

# Custom colors for the completion menu, toolbar, etc.
[colors]
# Completion menus.
Token.Menu.Completions.Completion.Current = 'bg:#00aaaa #000000'
Token.Menu.Completions.Completion = 'bg:#008888 #ffffff'
Token.Menu.Completions.MultiColumnMeta = 'bg:#aaffff #000000'
Token.Menu.Completions.ProgressButton = 'bg:#003333'
Token.Menu.Completions.ProgressBar = 'bg:#00aaaa'

# Query results
Token.Output.Header = 'bold'
Token.Output.OddRow = ''
Token.Output.EvenRow = ''

# Selected text.
Token.SelectedText = '#ffffff bg:#6666aa'

# Search matches. (reverse-i-search)
Token.SearchMatch = '#ffffff bg:#4444aa'
Token.SearchMatch.Current = '#ffffff bg:#44aa44'

# The bottom toolbar.
Token.Toolbar = 'bg:#222222 #aaaaaa'
Token.Toolbar.Off = 'bg:#222222 #888888'
Token.Toolbar.On = 'bg:#222222 #ffffff'

# Search/arg/system toolbars.
Token.Toolbar.Search = 'noinherit bold'
Token.Toolbar.Search.Text = 'nobold'
Token.Toolbar.System = 'noinherit bold'
Token.Toolbar.Arg = 'noinherit bold'
Token.Toolbar.Arg.Text = 'nobold'

# Favorite queries.
[favorite_queries]`

**Comment by houyaerda** [comment]
.myclirc

# vi: ft=dosini
[main]

# Enables context sensitive auto-completion. If this is disabled the all
# possible completions will be listed.
smart_completion = True

# Multi-line mode allows breaking up the sql statements into multiple lines. If
# this is set to True, then the end of the statements must have a semi-colon.
# If this is set to False then sql statements can't be split into multiple
# lines. End of line (return) is considered as the end of the statement.
multi_line = False

# Destructive warning mode will alert you before executing a sql statement
# that may cause harm to the database such as "drop table", "drop database"
# or "shutdown".
destructive_warning = True

# log_file location.
log_file = ~/.mycli.log

# Default log level. Possible values: "CRITICAL", "ERROR", "WARNING", "INFO"
# and "DEBUG". "NONE" disables logging.
log_level = INFO

# Log every query and its results to a file. Enable this by uncommenting the
# line below.
# audit_log = ~/.mycli-audit.log

# Timing of sql statments and table rendering.
timing = True

# Table format. Possible values: ascii, double, github,
# psql, plain, simple, grid, fancy_grid, pipe, orgtbl, rst, mediawiki, html,
# latex, latex_booktabs, textile, moinmoin, jira, vertical, tsv, csv.
# Recommended: ascii
table_format = ascii

# Syntax coloring style. Possible values (many support the "-dark" suffix):
# manni, igor, xcode, vim, autumn, vs, rrt, native, perldoc, borland, tango, emacs,
# friendly, monokai, paraiso, colorful, murphy, bw, pastie, paraiso, trac, default,
# fruity.
# Screenshots at http://mycli.net/syntax
syntax_style = default

# Keybindings: Possible values: emacs, vi.
# Emacs mode: Ctrl-A is home, Ctrl-E is end. All emacs keybindings are available in the REPL.
# When Vi mode is enabled you can use modal editing features offered by Vi in the REPL.
key_bindings = emacs

# Enabling this option will show the suggestions in a wider menu. Thus more items are suggested.
wider_completion_menu = False

# MySQL prompt
# \D - The full current date
# \d - Database name
# \h - Hostname of the server
# \m - Minutes of the current time
# \n - Newline
# \P - AM/PM
# \p - Port
# \R - The current time, in 24-hour military time (0–23)
# \r - The current time, standard 12-hour time (1–12)
# \s - Seconds of the current time
# \t - Product type (Percona, MySQL, Mariadb)
# \u - Username
prompt = '\t \u@\h:\d> '
prompt_continuation = '-> '

# Skip intro info on startup and outro info on exit
less_chatty = True

# Use alias from --login-path instead of host name in prompt
login_path_as_host = False

# Cause result sets to be displayed vertically if they are too wide for the current window,
# and using normal tabular format otherwise. (This applies to statements terminated by ; or \G.)
auto_vertical_output = False

# keyword casing preference. Possible values "lower", "upper", "auto"
keyword_casing = auto

# Custom colors for the completion menu, toolbar, etc.
[colors]
# Completion menus.
Token.Menu.Completions.Completion.Current = 'bg:#00aaaa #000000'
Token.Menu.Completions.Completion = 'bg:#008888 #ffffff'
Token.Menu.Completions.MultiColumnMeta = 'bg:#aaffff #000000'
Token.Menu.Completions.ProgressButton = 'bg:#003333'
Token.Menu.Completions.ProgressBar = 'bg:#00aaaa'

# Query results
Token.Output.Header = 'bold'
Token.Output.OddRow = ''
Token.Output.EvenRow = ''

# Selected text.
Token.SelectedText = '#ffffff bg:#6666aa'

# Search matches. (reverse-i-search)
Token.SearchMatch = '#ffffff bg:#4444aa'
Token.SearchMatch.Current = '#ffffff bg:#44aa44'

# The bottom toolbar.
Token.Toolbar = 'bg:#222222 #aaaaaa'
Token.Toolbar.Off = 'bg:#222222 #888888'
Token.Toolbar.On = 'bg:#222222 #ffffff'

# Search/arg/system toolbars.
Token.Toolbar.Search = 'noinherit bold'
Token.Toolbar.Search.Text = 'nobold'
Token.Toolbar.System = 'noinherit bold'
Token.Toolbar.Arg = 'noinherit bold'
Token.Toolbar.Arg.Text = 'nobold'

# Favorite queries.
[favorite_queries]

**Comment by houyaerda** [comment]
.myclirc

`# vi: ft=dosini`
`[main]`

`# Enables context sensitive auto-completion. If this is disabled the all`
`# possible completions will be listed.`
`smart_completion = True`

`# Multi-line mode allows breaking up the sql statements into multiple lines. If`
`# this is set to True, then the end of the statements must have a semi-colon.`
`# If this is set to False then sql statements can't be split into multiple`
`# lines. End of line (return) is considered as the end of the statement.`
`multi_line = False`

`# Destructive warning mode will alert you before executing a sql statement`
`# that may cause harm to the database such as "drop table", "drop database"`
`# or "shutdown".`
`destructive_warning = True`

`# log_file location.`
`log_file = ~/.mycli.log`

`# Default log level. Possible values: "CRITICAL", "ERROR", "WARNING", "INFO"`
`# and "DEBUG". "NONE" disables logging.`
`log_level = INFO`

`# Log every query and its results to a file. Enable this by uncommenting the`
`# line below.`
`# audit_log = ~/.mycli-audit.log`

`# Timing of sql statments and table rendering.`
`timing = True`

`# Table format. Possible values: ascii, double, github,`
`# psql, plain, simple, grid, fancy_grid, pipe, orgtbl, rst, mediawiki, html,`
`# latex, latex_booktabs, textile, moinmoin, jira, vertical, tsv, csv.`
`# Recommended: ascii`
`table_format = ascii`

`# Syntax coloring style. Possible values (many support the "-dark" suffix):`
`# manni, igor, xcode, vim, autumn, vs, rrt, native, perldoc, borland, tango, emacs,`
`# friendly, monokai, paraiso, colorful, murphy, bw, pastie, paraiso, trac, default,`
`# fruity.`
`# Screenshots at http://mycli.net/syntax`
`syntax_style = default`

`# Keybindings: Possible values: emacs, vi.`
`# Emacs mode: Ctrl-A is home, Ctrl-E is end. All emacs keybindings are available in the REPL.`
`# When Vi mode is enabled you can use modal editing features offered by Vi in the REPL.`
`key_bindings = emacs`

`# Enabling this option will show the suggestions in a wider menu. Thus more items are suggested.`
`wider_completion_menu = False`

`# MySQL prompt`
`# \D - The full current date`
`# \d - Database name`
`# \h - Hostname of the server`
`# \m - Minutes of the current time`
`# \n - Newline`
`# \P - AM/PM`
`# \p - Port`
`# \R - The current time, in 24-hour military time (0–23)`
`# \r - The current time, standard 12-hour time (1–12)`
`# \s - Seconds of the current time`
`# \t - Product type (Percona, MySQL, Mariadb)`
`# \u - Username`
`prompt = '\t \u@\h:\d> '`
`prompt_continuation = '-> '`

`# Skip intro info on startup and outro info on exit`
`less_chatty = True`

`# Use alias from --login-path instead of host name in prompt`
`login_path_as_host = False`

`# Cause result sets to be displayed vertically if they are too wide for the current window,`
`# and using normal tabular format otherwise. (This applies to statements terminated by ; or \G.)`
`auto_vertical_output = False`

`# keyword casing preference. Possible values "lower", "upper", "auto"`
`keyword_casing = auto`

`# Custom colors for the completion menu, toolbar, etc.`
`[colors]`
`# Completion menus.`
`Token.Menu.Completions.Completion.Current = 'bg:`#00aaaa `#000000'``
`Token.Menu.Completions.Completion = 'bg:`#008888 `#ffffff'``
`Token.Menu.Completions.MultiColumnMeta = 'bg:`#aaffff `#000000'``
`Token.Menu.Completions.ProgressButton = 'bg:`#003333'``
`Token.Menu.Completions.ProgressBar = 'bg:`#00aaaa'``

`# Query results`
`Token.Output.Header = 'bold'`
`Token.Output.OddRow = ''`
`Token.Output.EvenRow = ''`

`# Selected text.`
`Token.SelectedText = '`#ffffff bg:`#6666aa'``

`# Search matches. (reverse-i-search)`
`Token.SearchMatch = '`#ffffff bg:`#4444aa'``
`Token.SearchMatch.Current = '`#ffffff bg:`#44aa44'``

`# The bottom toolbar.`
`Token.Toolbar = 'bg:`#222222 `#aaaaaa'``
`Token.Toolbar.Off = 'bg:`#222222 `#888888'``
`Token.Toolbar.On = 'bg:`#222222 `#ffffff'``

`# Search/arg/system toolbars.`
`Token.Toolbar.Search = 'noinherit bold'`
`Token.Toolbar.Search.Text = 'nobold'`
`Token.Toolbar.System = 'noinherit bold'`
`Token.Toolbar.Arg = 'noinherit bold'`
`Token.Toolbar.Arg.Text = 'nobold'`

`# Favorite queries.`
`[favorite_queries]`

**Comment by houyaerda** [comment]
Now I find mycli can work in other window.And it already report wrong info when i use original window.Thank you anyway.
