### ISSUE TITLE
KeyError: 6 (cannot select null)

### ISSUE THREAD

**Issue by meeuw** [dbcli/mycli#515]
```
2017-09-20 09:15:04,574 (9540/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mycli/main.py", line 541, in one_iteration
    max_width)
  File "/usr/lib/python3.6/site-packages/mycli/main.py", line 850, in format_output
    for col in cur.description]
  File "/usr/lib/python3.6/site-packages/mycli/main.py", line 850, in <listcomp>
    for col in cur.description]
KeyError: 6
'
```
while executing:
```
select null;
```

**Comment by tsroten** [comment]
@meeuw Thanks for pointing this out! This is the same problem as #509 (the field type not being in [the conversion dict](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/converters.py#L389)), so I'm going to close this one and put a note on that issue.
