### ISSUE TITLE
AttributeError: module 'pymysql' has no attribute 'cursors'

### ISSUE THREAD

**Issue by AnthonyWC** [dbcli/mycli#521]
I installed a few pip modules related to python/sql and I am seeing this error with mycli:

```
mycli -u root -h localhost  
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.5.2', 'console_scripts', 'console')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/mycli/mycli/main.py", line 36, in <module>
    from .sqlexecute import SQLExecute
  File "/usr/share/mycli/mycli/sqlexecute.py", line 4, in <module>
    from .packages import connection, special
  File "/usr/share/mycli/mycli/packages/connection.py", line 9, in <module>
    Cursor = pymysql.cursors.Cursor
AttributeError: module 'pymysql' has no attribute 'cursors'

(pip3)
mysqlclient (1.3.12)                                             - Python interface to MySQL
  INSTALLED: 1.3.12 (latest)

PyMySQL (0.7.11)                                                 - Pure Python MySQL Driver
  INSTALLED: 0.7.11 (latest)

PyMySQL3 (0.5)                                                   - Pure Python MySQL Driver
  INSTALLED: 0.5 (latest)
```

**Comment by AnthonyWC** [comment]
Reinstall pymysql fixed it.
