### ISSUE TITLE
mycli conflict with pbr

### ISSUE THREAD

**Issue by lloy** [dbcli/mycli#538]
in mycli entry_points  have context :
test:
tasks:
when i run python setup.py install in my test of project 
there are something wrong:
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pbr/core.py", line 115, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 267, in cfg_to_args
    wrap_commands(kwargs)
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 576, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named tasks

**Comment by tsroten** [comment]
This is something we should fix. Here is a related PR in CLI Helpers: https://github.com/dbcli/cli_helpers/pull/29
