### ISSUE TITLE
error  (1045, "Access denied xxxx (using password: NO)") with MySQL 8

### ISSUE THREAD

**Issue by xueshichaoya** [dbcli/mycli#595]
hi,
    it seems somethings wrong with MySQL8, and i find someone has the similar problem,  i check the version of pymysql (0.8.0), modify mysql's init_connect "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci', this id is 246",but it's not OK.

==============HERE IS THE LOG====================================
➜  ~ mycli -u bloguser 
Password: 
(1045, "Access denied for user 'bloguser'@'localhost' (using password: NO)")
➜  ~ cat .mycli.log               

2018-04-21 17:15:03,226 (28788/MainThread) mycli.config ERROR - Unable to parse line None of config file '/etc/mysql/my.cnf'.
2018-04-21 17:15:03,226 (28788/MainThread) mycli.config ERROR - Using successfully parsed config values.
2018-04-21 17:15:03,227 (28788/MainThread) mycli.config ERROR - Unable to parse line None of config file '/etc/mysql/my.cnf'.
2018-04-21 17:15:03,227 (28788/MainThread) mycli.config ERROR - Using successfully parsed config values.
2018-04-21 17:15:06,326 (28788/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/main.py", line 390, in _connect\n    socket, charset, local_infile, ssl)\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/sqlexecute.py", line 52, in __init__\n    self.connect()\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/sqlexecute.py", line 88, in connect\n    conv=conv, ssl=ssl)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect\n    return Connection(*args, **kwargs)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__\n    self.connect()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 936, in connect\n    self._request_authentication()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in _request_authentication\n    auth_packet = self._read_packet()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet\n    packet.check_error()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error\n    err.raise_mysql_exception(self._data)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1045, "Access denied for user \'bloguser\'@\'localhost\' (using password: NO)")\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/main.py", line 424, in connect\n    raise e\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/main.py", line 406, in connect\n    _connect()\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/main.py", line 396, in _connect\n    socket, charset, local_infile, ssl)\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/sqlexecute.py", line 52, in __init__\n    self.connect()\n  File "/opt/anaconda3/lib/python3.6/site-packages/mycli/sqlexecute.py", line 88, in connect\n    conv=conv, ssl=ssl)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect\n    return Connection(*args, **kwargs)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__\n    self.connect()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 936, in connect\n    self._request_authentication()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in _request_authentication\n    auth_packet = self._read_packet()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet\n    packet.check_error()\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error\n    err.raise_mysql_exception(self._data)\n  File "/opt/anaconda3/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1045, "Access denied for user \'bloguser\'@\'localhost\' (using password: NO)")\n'

**Comment by meeuw** [comment]
You shouldn't need to change the collation if you use the latest version of pymysql (which added mysql 8 support).

Could you please check your version of pymysql? It should be v0.8.0.

**Comment by xueshichaoya** [comment]
hi, the version is 0.8.0

➜  ~ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>> pymysql.VERSION
(0, 8, 0, None)
>>>

**Comment by xueshichaoya** [comment]
hi ,i have solve the problem . today i reinstall MySQL8.0.1, and this time i choose the second option（such as xxx5.7xxx）when i was asked  to choose a authentication_plugin for the root user .and then I was surprised to find that i can use mycli tools, hahaha~~~ 。

Anyway, thank you for all your help!

**Comment by meeuw** [comment]
Great! Thank you for letting us know!

**Comment by FlyYangke** [comment]
@xueshichaoya  I meet the same problem. I use yum repopository to install mysql8. What do you mean that  ' i choose the second option（such as xxx5.7xxx）when i was asked to choose a authentication_plugin for the root user'.  Install mysql5.7 or other? I don`t meet that choice. Installing method https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/

**Comment by neewbee** [comment]
see [upgrade-caching-sha2-password](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password)
you can change to 
```mysql
 ALTER USER user
  IDENTIFIED WITH caching_sha2_password
  BY 'password';
```
I think you can file an issue about this
