### ISSUE TITLE
Not all grants for user caused a lot of warnings

### ISSUE THREAD

**Issue by wsmolak** [dbcli/mycli#721]
Hi,

when I connect with the user with priviliges only for one database it causes a lot of "noise" on the screen.
It's happening even with log_level = NONE

How can we remove such information?
Following is what I see on the screen: 

> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib64/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.6/site-packages/mycli/completion_refresher.py", line 63, in _bg_refresh
>     refresher(completer, executor)
>   File "/usr/local/lib/python3.6/site-packages/mycli/completion_refresher.py", line 90, in refresh_databases
>     completer.extend_database_names(executor.databases())
>   File "/usr/local/lib/python3.6/site-packages/mycli/sqlexecute.py", line 234, in databases
>     cur.execute(self.databases_query)
>   File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
>     result = self._query(query)
>   File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
>     conn.query(q)
>   File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
>     result.read()
>   File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
>     first_packet = self.connection._read_packet()
>   File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
>     packet.check_error()
>   File "/usr/local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
>     raise errorclass(errno, errval)
> pymysql.err.InternalError: (1227, 'Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation')

**Comment by scottnemes** [comment]
Could not reproduce this with any log_level. If this is still an issue, please give more details for a test case with user permissions and command.

@rolandwalker This should be safe to close barring any further details.
