### ISSUE TITLE
windows install mycli find error

### ISSUE THREAD

**Issue by Sunyelw** [dbcli/mycli#740]
python version:
`pip 19.1.1 from e:\python\ws\lib\site-packages\pip (python 3.7)`

cmd run
`pip install -U mycli`

however find error:

> Collecting mycli
  Using cached https://files.pythonhosted.org/packages/f9/8a/9f96f12b482ff2e1bbb1d4252e14b4a24ed37daa5b1dcd14c3d990eca9dd/mycli-1.19.0-py2.py3-none-any.whl
Collecting click>=4.1 (from mycli)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting Pygments>=1.6 (from mycli)
  Using cached https://files.pythonhosted.org/packages/6e/00/c5cb5fc7c047da4af049005d0146b3a961b1a25d9cefbbe24bf0882a11ad/Pygments-2.4.0-py2.py3-none-any.whl
Collecting configobj>=5.0.5 (from mycli)
  Using cached https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting sqlparse<0.3.0,>=0.2.2 (from mycli)
  Downloading https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Collecting cli-helpers[styles]>=1.0.1 (from mycli)
  Using cached https://files.pythonhosted.org/packages/ec/1b/dbf640a2553391ac837cc246acac0d4edd4b89e1c08d61ba91be8c4929e4/cli_helpers-1.2.0-py3-none-any.whl
Collecting cryptography>=1.0.0 (from mycli)
  Downloading https://files.pythonhosted.org/packages/af/38/b53b461982d4c9fd9693beb7b6c6d77edd4fe7ceac7822aeb2a5754ccb15/cryptography-2.6.1-cp37-cp37m-win32.whl (1.2MB)
     |██████████████                  | 552kB 13kB/s eta 0:00:52ERROR: Exception:
Traceback (most recent call last):
  File "e:\python\ws\lib\site-packages\pip\_vendor\urllib3\response.py", line 360, in _error_catcher
    yield
  File "e:\python\ws\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "e:\python\ws\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "e:\python\ws\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "e:\python\ws\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "e:\python\ws\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "e:\python\ws\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "e:\python\ws\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "e:\python\ws\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "e:\python\ws\lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "e:\python\ws\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "e:\python\ws\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "e:\python\ws\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "e:\python\ws\lib\site-packages\pip\_internal\operations\prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 886, in unpack_url
    progress_bar=progress_bar
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 746, in unpack_http_url
    progress_bar)
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 954, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "e:\python\ws\lib\site-packages\pip\_internal\utils\hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 651, in written_chunks
    for chunk in chunks:
  File "e:\python\ws\lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "e:\python\ws\lib\site-packages\pip\_internal\download.py", line 640, in resp_read
    decode_content=False):
  File "e:\python\ws\lib\site-packages\pip\_vendor\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "e:\python\ws\lib\site-packages\pip\_vendor\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "e:\python\ws\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "e:\python\ws\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

any suggestion? thx a lot.

**Comment by tsroten** [comment]
Hello! It looks like there was an issue with pip downloading the required packages — the network connection timed out. It was probably a temporary issue. If you try again does it work?

**Comment by Sunyelw** [comment]
Thx, it does matter of network.

I used this command resolved it.

`pip install -U mycli -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com`
