### ISSUE TITLE
Exception in thread Thread-260

### ISSUE THREAD

**Issue by arael** [dbcli/mycli#754]
Hi,
while using mycli I have encountered this exception:

```
Exception in thread Thread-260:
Traceback (most recent call last):                                               
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 95, in extract_from_part
    raise StopIteration                                                          
StopIteration                                                                    
                                                                                 
The above exception was the direct cause of the following exception:             
                                                                                 
Traceback (most recent call last):                                                                                                                                                                               
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/mycli/mycli/sqlcompleter.py", line 258, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 93, in suggest_type
    full_text, identifier)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 203, in suggest_based_on_last_token
    return [{'type': 'column', 'tables': extract_tables(full_text)}]
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 154, in extract_tables
    return list(extract_table_identifiers(stream))
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 113, in extract_table_identifiers
    for item in token_stream:
RuntimeError: generator raised StopIteration


```

The query I was typing was this one: **update mdl_config_plugins set v**

After typing v the shell crashed. I did type the wrong name of the column so that might be what fired the exception.

The database is from Moodle 3.6.4+ (Build: 20190628).

I was able to continue as the shell didn't crash.

Let me know if you need more info. I will gladly provide.

Thank you for this shell, it is very useful.

**Comment by j-bennet** [comment]
This requires a port of fix from pgcli:

https://github.com/dbcli/pgcli/pull/971

**Comment by meldafert** [comment]
@arael what version are you using? ubuntu has only mycli 1.16.0 for ubuntu 19.10, which was before #619 was fixed (included in 1.18.0)

**Comment by arael** [comment]
mycli --version
Version: 1.16.0

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

Since this was already fixed I will close the issue. Will get the fix once I upgrade to Ubuntu 19.10.

Thank you for replying.

**Comment by meldafert** [comment]
oh, to clarify: upgrading to ubuntu 19.10 does not help (it has 1.16.0 as well).
if you want the newest version of mycli, you want to install it using pip3:
`sudo apt install python3-pip`
`sudo pip3 install mycli`

**Comment by arael** [comment]
Thank you very much for the suggestion. I will do that.
