### ISSUE TITLE
mycli call got shut down when I use the completion function

### ISSUE THREAD

**Issue by bellsmarket** [dbcli/mycli#783]
I installed mycli on kalilinux.

When using the completion function in Mycli, it often shuts down.

Are there any countermeasures?
Thank you for your cooperation.

```
SQLstatment  Exception in thread Thread-91:
Traceback (most recent call last):                                              
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 95, in extract_from_part
    raise StopIteration                                                         
StopIteration                                                                   
                                                                                
The above exception was the direct cause of the following exception:            
                                                                                
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/mycli/mycli/sqlcompleter.py", line 258, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 93, in suggest_type
    full_text, identifier)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 203, in suggest_based_on_last_token
    return [{'type': 'column', 'tables': extract_tables(full_text)}]
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 154, in extract_tables
    return list(extract_table_identifiers(stream))
  File "/usr/share/mycli/mycli/packages/parseutils.py", line 113, in extract_table_identifiers
    for item in token_stream:
RuntimeError: generator raised StopIteration
```

**Comment by pasenor** [comment]
Hi, looks like a query parsing problem. Do you happen to know the query that caused the crash?

**Comment by bellsmarket** [comment]
ex. Insert into animals values()

**Comment by bellsmarket** [comment]
Hi 
I don't use special difficult queries.
Mycli crashes even with simple queries.

It often crashes when I type parentheses.
ex. Insert into _tabels_ values( _column_ _val_);

Thank you for your reply.

**Comment by pasenor** [comment]
>   File "/usr/share/mycli/mycli/packages/parseutils.py", line 95, in extract_from_part
    raise StopIteration                                                         


What version are you using? (you can check with `mycli --version`)
An issue with this line was fixed in 1.18.0

**Comment by tvjg** [comment]
Upgrading resolved this issue for me. I was using mycli 1.16.0 (from Ubuntu 18.04 repos). I uninstalled and used pip to grab 1.20.0. Everything seems to be functioning smoothly now.

**Comment by bellsmarket** [comment]
I was using mycli 1.16.0 too (from Kali Linux repos).
Mycli cannot be updated from _apt_.
Does it look best to use with _pip_?

**Comment by pasenor** [comment]
Yes, `pip install --upgrade mycli`.
Distro packages are not always up-to-date.

**Comment by bellsmarket** [comment]
I upgraded mycli to 1.20.1.
The error that occurred when entering Parentheses was
No longer at all.

Leave a log when someone browses.
