### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'sqlparse<0.3.0,>=0.2.2' distribution was not found and is required by mycli.. on Backbox Linux

### ISSUE THREAD

**Issue by AzhariRamadhan** [dbcli/mycli#812]
i used backbox 6 base on ubuntu 18.04 LTS
repo-> https://packages.ubuntu.com/bionic/database/mycli
version - 1.8.1-2

**Traceback (most recent call last):
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (sqlparse 0.3.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('sqlparse<0.3.0,>=0.2.2'), {'mycli'})**

During handling of the above exception, another exception occurred:

**Traceback (most recent call last):
  File "/usr/bin/mycli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/cyber/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse<0.3.0,>=0.2.2' distribution was not found and is required by mycli**

**Comment by rolandwalker** [comment]
Closing since this is a packager issue, and is probably fixed in any case.
