### ISSUE TITLE
mycli in Debian 8 can not run.

### ISSUE THREAD

**Issue by Gnouc** [dbcli/mycli#83]
I'm in Debian 8, install `mycli` with:
```
sudo pip install mycli
```

Then calling `mycli` always give the error:
```
$ mycli -h localhost -u root
__init__() got an unexpected keyword argument 'password'
$ mycli -h localhost -u root -p
Password: 
__init__() got an unexpected keyword argument 'password'
```

**Comment by amjith** [comment]
@Gnuoc Can you paste the output from `~/.mycli.log` file? 

I'm unable to reproduce the error on a debian VM.

**Comment by Gnouc** [comment]
@amjith: Here it is
```
2015-07-31 00:12:38,903 (10413/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/mycli/main.py", line 202, in connect\n    socket, charset)\n  File "/usr/local/lib/python2.7/dist-packages/mycli/sqlexecute.py", line 39, in __init__\n    self.connect()\n  File "/usr/local/lib/python2.7/dist-packages/mycli/sqlexecute.py", line 59, in connect\n    client_flag=pymysql.constants.CLIENT.INTERACTIVE)\n  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 88, in Connect\n    return Connection(*args, **kwargs)\nTypeError: __init__() got an unexpected keyword argument \'password\'\n'
```
After some digging, I think the problem is line 56 in `sqlexecute.py`. It called `pymysql.connect` with `password` as keyword argument, while my `pymysql` version used `passwd` instead of `password`:
```
Class docstring:
            Establish a connection to the MySQL database. Accepts several
            arguments:
    
            host: Host where the database server is located
            user: Username to log in as
            passwd: Password to use.
```

I changed it to `passwd` then the issue gone, but I got another issue:
```
2015-07-31 00:30:30,274 (10732/MainThread) mycli.main ERROR - Error parsing u'/etc/mysql/my.cnf'.
2015-07-31 00:30:30,274 (10732/MainThread) mycli.main ERROR - Recovering partially parsed config values.
```

**Comment by Gnouc** [comment]
@amjith I upgraded `pymysql` to `0.6.6` and all issue gone.

**Comment by amjith** [comment]
That was a good fine. I'll pin the minimum version for pymysql to be >= 0.6.6

Thank you!
