### ISSUE TITLE
Exception in thread completion_refresh

### ISSUE THREAD

**Issue by dchaofei** [dbcli/mycli#840]
$ mycli -d xxx_database
mysql 5.6.16-log
mycli 1.20.1
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Terje Røsten
xxxx_table> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/mycli/1.20.1_1/libexec/lib/python3.7/site-packages/mycli/completion_refresher.py", line 63, in _bg_refresh
    refresher(completer, executor)
  File "/usr/local/Cellar/mycli/1.20.1_1/libexec/lib/python3.7/site-packages/mycli/completion_refresher.py", line 102, in refresh_tables
    completer.extend_columns(executor.table_columns(), kind='tables')
  File "/usr/local/Cellar/mycli/1.20.1_1/libexec/lib/python3.7/site-packages/mycli/sqlcompleter.py", line 174, in extend_columns
    metadata[self.dbname][relname].append(column)
KeyError: '`1673315`'

**Comment by pasenor** [comment]
Hi, if before that error you had dropped a database, then it may be related to an error that was fixed in the latest release (#819 )
Please consider updating mycli to the version 1.21.1.
I'm sorry it took so long to respond.

**Comment by dchaofei** [comment]
Thanks, the problem is solved.
