### ISSUE TITLE
cannot import name 'convert_mysql_timestamp' from 'pymysql.converters'

### ISSUE THREAD

**Issue by Leon-Huang** [dbcli/mycli#884]
while typing `mycli` command in the terminal, it displays a lot errers:
```
PS C:\Users\leon> mycli
Traceback (most recent call last):
  File "D:\Python\Python38-32\Scripts\mycli-script.py", line 11, in <module>
    load_entry_point('mycli==1.21.1', 'console_scripts', 'mycli')()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\python\python38-32\lib\site-packages\mycli-1.21.1-py3.8.egg\mycli\main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "d:\python\python38-32\lib\site-packages\mycli-1.21.1-py3.8.egg\mycli\sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (d:\python\python38-32\lib\site-packages\pymysql\converters.py)
```

### enviroment:
win10 pro
```
PS C:\Users\leon> python -V
Python 3.8.4
```
```
mysql> status
--------------
C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe  Ver 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)

Connection id:          8
Current database:
Current user:           root@localhost
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384
Using delimiter:        ;
Server version:         8.0.21 MySQL Community Server - GPL
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    gbk
Conn.  characterset:    gbk
TCP port:               3306
Binary data as:         Hexadecimal
Uptime:                 4 hours 34 min 42 sec

Threads: 2  Questions: 5  Slow queries: 0  Opens: 115  Flush tables: 3  Open tables: 36  Queries per second avg: 0.000
--------------

mysql>
```

### what I have tried
I've use pip command to uninstall and reinstall `mycli`, but theres' still the same error
not sure what to do now...

**Comment by pasenor** [comment]
It's the same problem as in #882
PyMySQL released a new version that breaks some API that we use. Hopefully will be fixed soon, for now you can downgrade   PyMYSQL:
```
pip3 install -I PyMySQL==0.9.2
```
