### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlparse.sql'

### ISSUE THREAD

**Issue by ztoiax** [dbcli/mycli#903]
General users can run it,
but the **root** user will be error.
```sh
> sudo mycli
Traceback (most recent call last):
  File "/usr/bin/mycli", line 5, in <module>
    from mycli.main import cli
  File "/usr/lib/python3.8/site-packages/mycli/main.py", line 24, in <module>
    from mycli.packages.parseutils import is_dropping_database
  File "/usr/lib/python3.8/site-packages/mycli/packages/parseutils.py", line 3, in <module>
    from sqlparse.sql import IdentifierList, Identifier, Function
ModuleNotFoundError: No module named 'sqlparse.sql'

```
**sqlparse** module is already **installed**.
```sh
>pip3 list | grep sqlparse
sqlparse          0.3.1
```

**Comment by eigan** [comment]
Fixed in https://github.com/dbcli/mycli/pull/900

**Comment by pasenor** [comment]
Running mycli under root is problematic, because it leverages your python environment that is typically configured with environment variables. Why do you need root? If the reason is to connect to the database under the `root` user, just use `--user root`
