### ISSUE TITLE
Left join auto completion bug

### ISSUE THREAD

**Issue by JeffCarpenter** [dbcli/mycli#99]
First off, thanks for the great tool. I love how autocomplete knows to add tildes around table names.

Now the bug. I was doing a big left join, and I can't remember what keystroke I hit or reproduce the bug so far, but here's what I've got on my screen:

```python
mysql root@localhost:postillion> select * from `company-full-payment` f left join `company-deposit-requirements` d,Exception in thread Thread-2563:;
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 482, in run
    CompleteEvent(text_inserted=True)))
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/sqlcompleter.py", line 238, in get_completions                                       
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/packages/completion_engine.py", line 85, in suggest_type
    full_text, identifier)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/packages/completion_engine.py", line 267, in suggest_based_on_last_token
    prev_keyword, text_before_cursor, full_text, identifier)
  File "/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/packages/completion_engine.py", line 209, in suggest_based_on_last_token
    elif (token_v.endswith('join') and token.is_keyword) or (token_v in
AttributeError: 'unicode' object has no attribute 'is_keyword'
```

**Comment by amjith** [comment]
Sorry about the bug. It seems like the completion engine gets to an unstable state during JOINS. Someone else also encountered this bug earlier today. 

https://github.com/dbcli/mycli/issues/93

I'll track it down tonight and have a fix for it soon. 

Thanks for reporting it.

**Comment by amjith** [comment]
This bug is now fixed in master. I'll try to release a new version sometime this weekend. But until then you can install directly from master using pip as follows: 

```
pip install https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by JeffCarpenter** [comment]
Wow, that was *very* prompt. Thank you!
