### ISSUE TITLE
set column max_width

### ISSUE THREAD

**Issue by potoo0** [dbcli/mycli#992]
Is it possible to support setting maximum width for column?

example:
org result:
```
+----+-------+---------------------+---------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | job_name | start_time          | end_time            | elapsed | status | details                                                                                                                                                           

      |
+----+-------+---------------------+---------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9  | test01   | 2021-04-22 17:16:30 | 2021-04-22 17:16:30 | 0s      | failed | 2021-04-22 17:16:30,321 - test01 - e:\algo_factory\logtodb\test.py[line:28]-ERROR: 1 / 0\nTraceback (most recent call last):\n  File "e:\algo_factory\logtodb\test.py", line 26, in main\n    1 / 0\nZeroDivisionError: division by zero\n |
| 10 | test02   | 2021-04-22 17:16:55 | 2021-04-22 17:16:55 | 2s      | failed | 2021-04-22 17:16:54,828 - test02 - e:\algo_factory\logtodb\test.py[line:28]-ERROR: 1 / 0\nTraceback (most recent call last):\n  File "e:\algo_factory\logtodb\test.py", line 26, in main\n    1 / 0\nZeroDivisionError: division by zero\n |
+----+-------+---------------------+---------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
Expect the output after setting max_width:
```
+----+-------+---------------------+---------------------+---------+--------+---------------------+
| id | job_name | start_time          | end_time            | elapsed | status | details    |
+----+-------+---------------------+---------------------+---------+--------+---------------------+
| 9  | test01   | 2021-04-22 17:16:30 | 2021-04-22 17:16:30 | 0s      | failed | 2021-04-22 17:16... |
| 10 | test02   | 2021-04-22 17:16:55 | 2021-04-22 17:16:55 | 2s      | failed | 2021-04-22 17:16... |
+----+-------+---------------------+---------------------+---------+--------+---------------------+
```

**Comment by rolandwalker** [comment]
Hi!  After some deliberation, I think this is out of scope for us.  The issue is that setting the value would be awkward.  Our main method for configuration is the `~/.myclirc` configuration file.  It seems unlikely that the user would have a permanent value for `max_width` in the config file, and equally unlikely that the user would restart mycli after editing the config file for a onetime setting.

The other possibility would be a backslash "special" command.  We don't have a `\set variable=value` at this time, and `\max_width` seems too special-purpose to create at the toplevel.

We could revisit this in the future if someone implements `\set variable=value`.
